### ISSUE TITLE
[bug] Deep Bump (mtb), axes don't match array

### ISSUE THREAD

**Issue by TurningTide** [melMass/comfy_mtb#102]
### Describe the bug

Deep Bump (mtb) node does not work. 

### Reproduction

1. Add node Load Image to load texture
2. Add Deep Bump (mtb)
3. Add Preview/Save Image
4. Connect Load Image with Deep Bump and Deep Bump with Preview Image

![image](https://github.com/melMass/comfy_mtb/assets/9952059/68c639c4-8eda-490c-bbc7-a63f53c7690c)

### Expected behavior

Normal map is generated and rendered in Preview Image

### Operating System

Windows (Default)

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Console output

```sh
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\_AI\ComfyUIMain\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\_AI\ComfyUIMain\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\_AI\ComfyUIMain\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\_AI\ComfyUIMain\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 283, in apply
    in_img = np.transpose(image, (2, 0, 1)) / 255
  File "F:\_AI\ComfyUIMain\comfy_ui\lib\site-packages\numpy\core\fromnumeric.py", line 655, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "F:\_AI\ComfyUIMain\comfy_ui\lib\site-packages\numpy\core\fromnumeric.py", line 56, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "F:\_AI\ComfyUIMain\comfy_ui\lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
ValueError: axes don't match array

Prompt executed in 0.08 seconds
```

**Comment by melMass** [comment]
Thanks the simple example from your screenshot should definitely work but I'm not using it a lot so I will test it further and add it to the [examples](https://github.com/melMass/comfy_mtb/wiki/Examples)

**Comment by melMass** [comment]
Oh yes there is a few issues! I will fix them now

**Comment by melMass** [comment]
Fixed in the next commit, there was plenty of issues with it :)

![image](https://github.com/melMass/comfy_mtb/assets/7041726/1172ef09-7539-4910-9995-572572d6ae2f)

I will also add an example:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/bcaaa882-bdc7-4cda-af24-f93a37db7715)

**Comment by melMass** [comment]
@TurningTide I added a few related nodes to generate seamless textures from sd, you can check the [Examples](https://github.com/melMass/comfy_mtb/wiki/Examples): 

<p><img align=top width=512 src="https://github.com/melMass/comfy_mtb/assets/7041726/9db516b5-45d2-4389-b904-b3a94660f24c"/></p><p><img align=top width=512 src="https://github.com/melMass/comfy_mtb/assets/7041726/7e4477f6-8e18-4839-9864-83d07d6690a1"/></p>
