### ISSUE TITLE
[bug]  Setuptools is replacing distutils - Warning message

### ISSUE THREAD

**Issue by Suzie1** [melMass/comfy_mtb#104]
### Describe the bug

F:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

### Reproduction

warning message occurs on startup of comfyui

### Expected behavior

may not be a bug, could be working as intended

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks, yep this can be safely ignored
