### ISSUE TITLE
[bug] IndexError: list index out of range

### ISSUE THREAD

**Issue by Piscabo** [melMass/comfy_mtb#106]
### Describe the bug

Stops me from using anything (nodes) from MTB

### Reproduction

General error, it does not point to a specific. Noad. All loads fine:
[comfy_mtb] | WARNING -> Web extensions folder at A:\AI_Files\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | STATUS -> Loaded the following nodes:
        Animation Builder (mtb): Convenient way to manage basic animation maths at the core of many of my workflows
        Smart Step (mtb): Utils to control the steps start/stop of the KAdvancedSampler in percentage
        Styles Loader (mtb): Load csv files and populate a dropdown from the rows (à la A111)
        Interpolate Clip Sequential (mtb): -
        Bbox From Mask (mtb): From a mask extract the bounding box
        Bbox (mtb): The bounding box (BBOX) custom type used by other nodes
        Crop (mtb): Crops an image and an optional mask to a given bounding box
        Uncrop (mtb): Uncrops an image to a given bounding box
        Debug (mtb): Experimental node to debug any Comfy values, support for more types and widgets is planned
        Save Tensors (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Deep Bump (mtb): Normal & height maps generation from single pictures
        Restore Face (mtb): Uses GFPGan to restore faces
        Load Face Enhance Model (mtb): Loads a GFPGan or RestoreFormer model for face enhancement.
        Face Swap (mtb): Face swap using deepinsight/insightface models
        Load Face Swap Model (mtb): Loads a faceswap model
        Load Face Analysis Model (mtb): Loads a face analysis model
        Qr Code (mtb): Basic QR Code generator
        Unsplash Image (mtb): Unsplash Image given a keyword and a size
        Text To Image (mtb): Utils to convert text to image using a font
        String Replace (mtb): Basic string replacement
        Fit Number (mtb): Fit the input float using a source and target range
        Get Batch From History (mtb): Very experimental node to load images from the history of the server.
        Any To String (mtb): Tries to take any input and convert it to a string
        Load Film Model (mtb): Loads a FILM model
        Film Interpolation (mtb): Google Research FILM frame interpolation for large motion
        Concat Images (mtb): Add images to batch
        Color Correct (mtb): Various color correction methods
        Image Compare (mtb): Compare two images and return a difference image
        Image Tile Offset (mtb): Mimics an old photoshop technique to check for seamless textures
        Blur (mtb): Blur an image using a Gaussian filter.
        Mask To Image (mtb): Converts a mask (alpha) to an RGB image with a color and background
        Colored Image (mtb): Constant color image of given size
        Image Premultiply (mtb): Premultiply image with mask
        Image Resize Factor (mtb): Extracted mostly from WAS Node Suite, with a few edits (most notably multiple image support) and less features.
        Save Image Grid (mtb): Save all the images in the input batch as a grid of images.
        Load Image From Url (mtb): Load an image from the given URL
        Stack Images (mtb): Stack the input images horizontally or vertically
        Save Gif (mtb): Save the images from the batch as a GIF
        Export With Ffmpeg (mtb): Export with FFmpeg (Experimental)
        Latent Lerp (mtb): Linear interpolation (blend) between two latent vectors
        Image Remove Background Rembg (mtb): Removes the background from the input using Rembg.
        Model Patch Seamless (mtb): -
        Vae Decode (mtb): Wrapper for the 2 core decoders but also adding the sd seamless hack, taken from: FlyingFireCo/tiled_ksampler
        Float To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" FLOAT to a NUMBER.
        Int To Bool (mtb): Basic int to bool conversion
        Int To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" INT to a NUMBER.
        Transform Image (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Load Image Sequence (mtb): Load an image sequence from a folder. The current frame is used to determine which image to load.
        Save Image Sequence (mtb): Save an image sequence to a folder. The current frame is used to determine which image to save.

### Expected behavior

No index error should be reported that stops me from using ComfUI

### Operating System

Windows (Default)

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Console output

```sh
[ERROR] An error occurred while retrieving information for the 'Styles Loader (mtb)' node.
Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\server.py", line 417, in get_object_info
    out[x] = node_info(x)
  File "A:\AI_Files\ComfyUI\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "A:\AI_Files\ComfyUI\custom_nodes\comfy_mtb\nodes\conditions.py", line 160, in INPUT_TYPES
    cls.options[row[0]] = (row[1], row[2])
```

**Comment by melMass** [comment]
Do you have more informations since you had it working? Did it happened after a comfy update of something like that?

I'll test now with Comfy latest to be sure

**Comment by Piscabo** [comment]
> Do you have more informations since you had it working? Did it happened after a comfy update of something like that?
> 
> I'll test now with Comfy latest to be sure

Newest ComfUI Build
** ComfyUI start up time: 2023-10-07 11:28:09.450371
Total VRAM 12288 MB, total RAM 32706 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
VAE dtype: torch.bfloat16
Using xformers cross attention

As soon as I open the WebUI interface I get this error...
[ERROR] An error occurred while retrieving information for the 'Styles Loader (mtb)' node.
Traceback (most recent call last):
  File "A:\AI_Files\ComfyUI\server.py", line 417, in get_object_info
    out[x] = node_info(x)
  File "A:\AI_Files\ComfyUI\server.py", line 395, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "A:\AI_Files\ComfyUI\custom_nodes\comfy_mtb\nodes\conditions.py", line 160, in INPUT_TYPES
    cls.options[row[0]] = (row[1], row[2])
IndexError: list index out of range
