### ISSUE TITLE
[bug] Cannot call rmtree on a symbolic link !! Trying to start the node

### ISSUE THREAD

**Issue by xueqing0622** [melMass/comfy_mtb#113]
### Describe the bug

Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 119, in <module>
    shutil.rmtree(web_mtb)
  File "shutil.py", line 747, in rmtree
  File "shutil.py", line 745, in rmtree
OSError: Cannot call rmtree on a symbolic link

Cannot import F:\ComfyUI\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: Cannot call rmtree on a symbolic link
!! Trying to start the node

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
You need to pull the latest version: https://github.com/melMass/comfy_mtb/commit/25b933c698b250a411549d2600fae49bec225b7a

**Comment by xueqing0622** [comment]
I pull to 25b933c, even the lastest bb90e04 ,still same error show at startup CMD windows
![image](https://github.com/melMass/comfy_mtb/assets/114840118/4bcd75bd-d120-4c22-9af3-82befcfb2418)

**Comment by noteprince** [comment]
same problem~

**Comment by melMass** [comment]
Not sure why but since there are 5 alternatives to symlink on windows, maybe not all are compatible with python's os module.
You can manually delete the old web folder at ComfyUi/web/extension/mtb

**Comment by melMass** [comment]
I cannot reproduce but I added some instructions in case it fails: https://github.com/melMass/comfy_mtb/commit/278f22c2093b6eca63d2d00f7936774918707e4e

**Comment by xueqing0622** [comment]
It works, thx!
