### ISSUE TITLE
[bug] Unable to load seamless texture example workflow

### ISSUE THREAD

**Issue by suwagawaki** [melMass/comfy_mtb#117]
### Describe the bug

I am unable to load the seamless texture example workflow, although I am able to load both textures nodes. 

### Operating System

Linux

### Comfy Mode

Other (online services, containers etc..)

### Console output

```sh
Nothing in the console appears when attempting to load .json file for debugging purposes.
```

**Comment by melMass** [comment]
Hi, did you close this by mistake?
