### ISSUE TITLE
[bug] Parsing Error style.scv

### ISSUE THREAD

**Issue by Piscabo** [melMass/comfy_mtb#122]
### Describe the bug

[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative

### Reproduction

During server start, I am faced with this parsing error. It was not there before.
ComfyUI Revision: 1656 [2a23ba0b] | Released on '2023-11-07'

### Expected behavior

No parsing errors should happen as the style file complies
![image](https://github.com/melMass/comfy_mtb/assets/123719842/e5d510c2-35a4-4d27-8c3d-f0d7f41fbf07)

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
[comfy_mtb] | WARNING -> There was an error while parsing A:\AI_Files\ComfyUI\styles\styles.csv, make sure it respects A1111 format, i.e 3 columns name, positive, negative
```

### Additional context

![image](https://github.com/melMass/comfy_mtb/assets/123719842/0d930e61-f611-4881-8cf2-8c0532297f37)

**Comment by Piscabo** [comment]
This issue is new... my file did not change.

[styles.csv](https://github.com/melMass/comfy_mtb/files/13299092/styles.csv)

**Comment by melMass** [comment]
Thanks, I can see the warning indeed, but the file works fine for me:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/75f18cd4-7736-461a-a856-1d44e46b9bd1)
![image](https://github.com/melMass/comfy_mtb/assets/7041726/b5f08823-7c0c-45af-b29e-8e78113bfb40)


I will check why this is outputted
