### ISSUE TITLE
    Pick From Batch (mtb) [bug] 

### ISSUE THREAD

**Issue by Nebuluss** [melMass/comfy_mtb#130]
### Describe the bug

Can't load this node

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
I indeed forgot to push it before publishing the workflow 😬

**Comment by melMass** [comment]
Added in 16c1a59312b1d9841f5f8a814eff93a1ddf04edb thanks for the report

[mtb_svd_feedback_loop_v01.json](https://github.com/melMass/comfy_mtb/files/13501827/mtb_svd_feedback_loop_v01.json)
