### ISSUE TITLE
[bug] nodes not loading properly after installation 

### ISSUE THREAD

**Issue by xx88xx** [melMass/comfy_mtb#134]
### Describe the bug

Despite having MTB installed (using the manager)

I am still getting this error when trying to paste any workflow using the MTB nodes.

```
When loading the graph, the following node types were not found:
Restore Face (mtb)
Load Face Enhance Model (mtb)
Load Face Swap Model (mtb)
Load Face Analysis Model (mtb)
Face Swap (mtb)
Nodes that have failed to load will show as red on the graph.
```

![Screenshot 2023-12-12 g160407](https://github.com/melMass/comfy_mtb/assets/60696375/89d22049-068d-4f3a-aa07-eb2ce9ca44cc)

### Reproduction

When pasting this workflow from the MTB examples I get the error

https://github.com/melMass/comfy_mtb/blob/main/examples/01-faceswap.json

### Expected behavior

Nodes not red-ed out

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
When loading the graph, the following node types were not found:
Restore Face (mtb)
Load Face Enhance Model (mtb)
Load Face Swap Model (mtb)
Load Face Analysis Model (mtb)
Face Swap (mtb)
Nodes that have failed to load will show as red on the graph.
```

**Comment by Uniky** [comment]
same error after loading https://github.com/melMass/comfy_mtb/blob/main/examples/01-faceswap.json

**Comment by Uniky** [comment]
![image](https://github.com/melMass/comfy_mtb/assets/24896456/766b8f69-d2a4-494a-84c9-d6e9bb07a0ad)

error after loading https://github.com/melMass/comfy_mtb/blob/main/examples/02-film_interpolation.json

**Comment by melMass** [comment]
Please read https://github.com/melMass/comfy_mtb#optional-nodes

I don't provide support for these nodes on windows anymore they all have better options listed in the readme.
I will close this in favor of #128 for Linux and Mac though
