### ISSUE TITLE
[feat] Add a way to selectively activate js extensions

### ISSUE THREAD

**Issue by melMass** [melMass/comfy_mtb#136]
### Describe the problem

I kind of forgot about mtb's image feed since I don't use it and #135  made me think it could be useful to add a way to enable or disable "sub" extensions (for now mostly image feed)

### Describe the solution you'd like

-

**Comment by LoopControl** [comment]
+1 for option to disable image feed

**Comment by melMass** [comment]
Added in settings! You must reload the page for it to take effect and it will be persistent per client/browser (like the other settings)

![image](https://github.com/melMass/comfy_mtb/assets/7041726/4ca894d0-a15d-4bb5-9bb6-4aa76ae8a0df)
