### ISSUE TITLE
No module named 'facexlib'

### ISSUE THREAD

**Issue by Aljnk** [melMass/comfy_mtb#138]
### Describe the bug

Hi. When I start my ComfyUI I see your message `"No module named 'facexlib'"` from `custom_nodes\comfy_mtb\extern\GFPGAN\gfpgan\utils.py`

![image](https://github.com/melMass/comfy_mtb/assets/11256478/4ed2baf7-4d1f-43d7-8a6e-44ec19e2f547)

plus
`No module named 'tensorflow'`  from `\custom_nodes\comfy_mtb\nodes\image_interpolation.py`

### Reproduction

I Add to log.py this code (MTB_DEBUG=true):

logging.basicConfig(level=logging.DEBUG)
base_log_level = logging.DEBUG

and see in console

[comfy_mtb] | DEBUG -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'facexlib'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
[comfy_mtb] | DEBUG -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'facexlib'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by melMass** [comment]
Hi thanks for the report, this is "expected", these aren't automatically managed by mtb anymore (check #128 for more context, I will close this one in favor of it)

I will also rework the docs/readme soon as a lot is outdated
