### ISSUE TITLE
WARNING and ERROR

### ISSUE THREAD

**Issue by za-wa-n-go** [melMass/comfy_mtb#14]
[comfy_mtb] | WARNING -> cv2.ximgproc.guidedFilter not found, use opencv-contrib-python
[comfy_mtb] | ERROR -> Some nodes failed to load:
        Failed to import faceenhance because ModuleNotFoundError: No module named 'munch'
        Failed to import faceswap because ModuleNotFoundError: No module named 'ifnude'
        Failed to import fun because ModuleNotFoundError: No module named 'qrcode'
        Failed to import image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

**Comment by melMass** [comment]
Thanks! I will fix them before the next "release"!
Half are not needed and left overs, the other half should get installed... but my current approach for installing dependencies is not the best.

**Comment by melMass** [comment]
It should be fixed in main, you can also double check these install instructions (in progress): https://github.com/melMass/comfy_mtb/blob/dev/doc-and-examples/INSTALL.md which will live here in case you see this after the merge https://github.com/melMass/comfy_mtb/blob/main/INSTALL.md
