### ISSUE TITLE
[feat] Use of image mask to focus extraction

### ISSUE THREAD

**Issue by creeduk** [melMass/comfy_mtb#142]
### Describe the problem

When there is more in the foreground than you want. (Not an Issue just an idea)

### Describe the solution you'd like

 It might be interesting if an image had more than 1 person you could rough mask and have the extraction node now only focus on that part of the image

**Comment by melMass** [comment]
I'm not sure to understand this request!

Here is an example of what I understand you can just replace things with Foocus

[aworkflow.json](https://github.com/user-attachments/files/16458600/aworkflow.json)
![image](https://github.com/user-attachments/assets/db5d9eb8-adb5-4d1c-af8b-c6224619de18)

**Comment by creeduk** [comment]
Sorry it has been a while I think if I recall the extraction would find other people/things so being able to isolate what the extraction focused on by selecting an area it would have better chance to succeed.
