### ISSUE TITLE
[bug] debug node cannot work now

### ISSUE THREAD

**Issue by cardenluo** [melMass/comfy_mtb#145]
### Describe the bug

![image](https://github.com/melMass/comfy_mtb/assets/133877069/04be6d09-c2d1-4841-8272-757d74372fd7)
No input for the debug and math now

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Did this happen after an update of Comfy? I'll look into it a bit later today thanks for the report

**Comment by cardenluo** [comment]
![image](https://github.com/melMass/comfy_mtb/assets/133877069/15534f3e-0baf-47cc-b76b-a8ab783b4dd1)
![image](https://github.com/melMass/comfy_mtb/assets/133877069/229d9a12-6c80-4695-88df-b1dcd7a891c2)
There are no error prompts on the launcher, but there are some warnings on the web console. Could this be the cause?

**Comment by melMass** [comment]
It seems like there are multiple instances of mtb (or its web module) 
This can be because a few months back you had to manually move the web folder of extensions, now it's done automatically so I think you have mtb web extensions in ComfyUI/web/extensions <- if there is an mtb folder there just delete it

**Comment by cardenluo** [comment]
https://github.com/chflame163/ComfyUI_LayerStyle

![image](https://github.com/melMass/comfy_mtb/assets/133877069/f948cd4f-b033-4cc4-b6cc-90f789e65640)
thanks a lot ,And this plugin conflicts with it, this plugin will create files in web/extensions , delete it and then it's normal.

**Comment by chflame163** [comment]
> Thanks I will report it upstream they use the old method but I'mnot sure how it ended up interfering with mtb

Thank you mtb. I used the old version of the browser extension component and updated it to resolve the issue.

**Comment by alessandroperilli** [comment]
@melMass Any chance we can reopen this issue?

I'm having exactly the same problem experienced by @cardenluo, but I am not using LayerStyle custom node suite. So it must be something else.

This is the wonderful list of JS errors generated when I load ComfyUI with the latest commit and all custom node suites fetched to the latest version:

<img width="1728" alt="Screenshot 2024-04-27 at 12 13 02" src="https://github.com/melMass/comfy_mtb/assets/9775949/49b8caa8-9d9a-4a90-88b8-4c8ea3311aca">

Notice that my setup is composed of a macOS browser on a machine connecting to a local server on a Windows machine.
That said, the page is pointing to the right IP address in trying to load those js, and I can manually display the source code in the browser by simply clicking on the link in the Dev Tools.
