### ISSUE TITLE
[bug]  Text to Image node - no margin/padding

### ISSUE THREAD

**Issue by Ferniclestix** [melMass/comfy_mtb#150]
### Describe the bug

At first I thought feature request, but this can't be right. 
![Capture](https://github.com/melMass/comfy_mtb/assets/128430314/6a437d3c-e97d-495a-a9c8-e826fc5c35dc)
The text is too close to the edges to make the node even partially usable in an un-centered way.  There needs to be a safey gap along the edges so the text can still be readable.

### Expected behavior

ability to set a margin in pixel values to seperate text from borders

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
related wiki page: [Text to Image](https://github.com/melMass/comfy_mtb/wiki/nodes-text-to-image)
