### ISSUE TITLE
[bug]  Some nodes (4) could not be loaded

### ISSUE THREAD

**Issue by Elminsst** [melMass/comfy_mtb#151]
### Describe the bug

[36;20m[comfy_mtb] | INFO -> loaded [96m61[0m nodes successfuly[0m
[36;20m[comfy_mtb] | INFO -> Some nodes (4) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.[0m
![屏幕截图 2024-03-03 224448](https://github.com/melMass/comfy_mtb/assets/130235860/b4ed2a96-4291-4f6b-ab9b-a145cd45d050)

### Operating System

Windows (Default)

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

**Comment by HyperTwo** [comment]
the same problem

**Comment by baardev** [comment]
did you run the `python scripts/download_models.py`?

I had the same problem.  I ran that script and 3 of the 4 installed, but the FILM module failed with a "AttributeError: 'NoneType' object has no attribute 'groups'"
