### ISSUE TITLE
[comfy_mtb] | WARNING -> > No fonts found in the comfy folder, place at least one font file somewhere in ComfyUI's hierarchy

### ISSUE THREAD

**Issue by ErvinA-wx** [melMass/comfy_mtb#152]
### Describe the bug

![{17E6BC09-099A-42f4-9D20-59F4E0D638D5}](https://github.com/melMass/comfy_mtb/assets/153524252/356adcf6-35a8-42e3-be5e-c77bb4cfcebb)

### Reproduction

1、打开comfyui
2、控制台即显示“[comfy_mtb] | WARNING -> > No fonts found in the comfy folder, place at least one font file somewhere in ComfyUI's hierarchy”
3、将font文件复制到\comfy_mtb 文件夹下，复制到comfyui所有涉及font的文件夹下，仍然出现这个警告
4、删除“\comfy_mtb”则警告消失

### Expected behavior

1、告知如何手动解决这个问题。
2、下一次升级时自动解决这个问题。

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
嗨，埃尔文、

感谢您报告这个问题。
我已经在新版本中改进了警告功能，现在默认情况下会回退到字体！
如有需要，请随时发表评论，我们可以重新讨论这个问题。
