### ISSUE TITLE
pillow version upgraded to 10.0 or above

### ISSUE THREAD

**Issue by Pythonpa** [melMass/comfy_mtb#155]
### Describe the problem

Can you upgrad the pillow version required by mtb nodes beyond 10.0 or above? 

### Describe the solution you'd like

This node conflicts with some of the dependencies required by many other nodes, including comfyui's main program's required.

**Comment by melMass** [comment]
Hi,

[It's already the case](https://github.com/melMass/comfy_mtb/blob/54ff6583ded0ed4054f8e5d7fadf0b2350259dce/requirements.txt#L10)

**Comment by melMass** [comment]
Oh beyond? I had the opposite issue and decided to update since it broke mine, I'll had guards on the version then, thanks for the report
