### ISSUE TITLE
[bug]Colored Image (mtb) Unable to process batch masks

### ISSUE THREAD

**Issue by Fzz666123** [melMass/comfy_mtb#156]
### Describe the bug

VideoHelpersuite and Colored Image (mtb) use together  Unable to process batch images
![20240313225043](https://github.com/melMass/comfy_mtb/assets/163319247/221a4469-ff06-468c-85a8-0bbb09deb836)

Error occurred when executing Colored Image (mtb):

Cannot handle this data type: (1, 1, 512), |u1

File "T:\ComfyUI-aki-v1.2\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "T:\ComfyUI-aki-v1.2\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "T:\ComfyUI-aki-v1.2\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "T:\ComfyUI-aki-v1.2\custom_nodes\comfy_mtb\nodes\image_processing.py", line 519, in render_img
fg_masks = tensor2pil(foreground_mask)
File "T:\ComfyUI-aki-v1.2\custom_nodes\comfy_mtb\utils.py", line 289, in tensor2pil
Image.fromarray(
File "T:\ComfyUI-aki-v1.2\python\lib\site-packages\PIL\Image.py", line 3092, in fromarray
raise TypeError(msg) from e

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks for the report.
Can you attach a sample reproduction workflow?
Also, are you trying to batch masks, images, or both?

**Comment by melMass** [comment]
It works for batch images but not masks indeed:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/5aeb1128-d112-456d-b315-73f3fe7979b6)

**Comment by Fzz666123** [comment]
Yes, I'm getting an error when processing the image and mask at the same time.
Maybe batch masking will be supported in the future? Very much your answer!

**Comment by melMass** [comment]
It should be fixed now! Let me know

**Comment by Fzz666123** [comment]
Yes! It works! It's so amazing!
