### ISSUE TITLE
[Bug] Note+ node doesn't show text

### ISSUE THREAD

**Issue by alessandroperilli** [melMass/comfy_mtb#162]
### Describe the bug

The Note+ node is incredible useful, and it works perfectly. Thanks for sharing it with the community. 

Unfortunately, I can't see what I'm doing as the text is not visible in the node at all:
<img width="710" alt="Screenshot 2024-03-22 at 11 51 38" src="https://github.com/melMass/comfy_mtb/assets/9775949/3dfb75a1-f51f-499b-b7ce-1820d6c9e70d">

It behaves in this way either in HTML or Markdown mode. 

I checked the documentation but I couldn't find anything about this particular node.

Thank you for your help.

### Reproduction

1. Deploy the node on the canvas
2. Try to write some HTML/Markdown/plain text in it.

### Operating System

Mac

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Additional context

I use Vivaldi Browser (a flavor of Chrome).

**Comment by melMass** [comment]
Thanks for the report, I haven't seen this before, can you try on different browsers on your side to better pin point the issue?

If it still does it my first instinct would be an extension that applies some style overrides to Comfy, I've seen quite a few extensions doing this lately but both color and selected color seem strange.

**Comment by alessandroperilli** [comment]
Identical outcome on Safari. 
Of course, I have a number of additional node suites installed, but I'm not sure which one could be causing the conflict.

What can I do to debug this and give you more information?

**Comment by melMass** [comment]
Yes can you try this simple test:

[node_plus_bug.json](https://github.com/melMass/comfy_mtb/files/14725169/node_plus_bug.json)
![noteplusbug](https://github.com/melMass/comfy_mtb/assets/7041726/63896784-5d0e-4f83-b14e-18cec9b72501)

**Comment by alessandroperilli** [comment]
I loaded this json and I get the same identical problem:
<img width="1012" alt="Screenshot 2024-03-22 at 16 49 07" src="https://github.com/melMass/comfy_mtb/assets/9775949/02541407-427b-4aa5-99ba-df8f47a3fae5">
<img width="998" alt="Screenshot 2024-03-22 at 16 49 23" src="https://github.com/melMass/comfy_mtb/assets/9775949/26e6ad2c-27b6-4af6-af36-c82e80978490">

**Comment by melMass** [comment]
What does it look like if you unselect the text?
I'm going to expose the "editor theme" as a drop down or something maybe another theme will look better on your end
![noteplusbug+](https://github.com/melMass/comfy_mtb/assets/7041726/fa900b0f-f2ef-49e6-b27d-fdfcaa40cb1f)

**Comment by alessandroperilli** [comment]
It's simply empty, except for a few characters here and there in the markdown section. And, strangely, the whole font name in the previous example. 

<img width="785" alt="Screenshot 2024-03-22 at 17 50 36" src="https://github.com/melMass/comfy_mtb/assets/9775949/06fb5b8a-e30c-4ca8-aca0-9842624231ea">

With both Vivaldi and Safari, I have no web extensions loaded, so there's absolutely nothing at the browser level that could be interfering with this.

It has to be another ComfyUI node, as you suggested, but I need all of them for the [AP Workflow,](https://perilli.com/ai/comfyui/) and so I'm hoping we find a compatible middle ground.

Thanks for the time you are spending on this. I really appreciate it.

**Comment by melMass** [comment]
I exposed the themes in 133da70
Let me know

![noteplusbug++](https://github.com/melMass/comfy_mtb/assets/7041726/82bca77a-dc61-45d7-a130-214256683849)

**Comment by alessandroperilli** [comment]
Pulled, and tried all of them. No difference. I continue to see the same identical characters I saw in the original screenshots, just with a variation of background and foreground colors. 

I'm inclined to believe that this is not a theme problem. If so, I assume, I wouldn't be able to see even those few characters across the code. And why in the world the entirety of "IBM Plex Mono" would be visible if it's a theme problem?

This is a real mystery. 

If there's any other test I can do to debug this, please let me know.

**Comment by melMass** [comment]
I'm sure it's a simple issue but it's hard to pinpoint, can you screenshot your custom_nodes folder list?
I will check the extensions I don't use and install them. I regularly test mtb on windows and macos with "popular" extensions to check for conflicts like this but there are so many extensions popping up daily that it's hard to track.

**Comment by alessandroperilli** [comment]
Sure. This is my ComfyUI Manager snapshot:
[AP Workflow 9.0 EA4_nodes_snapshot.json](https://github.com/melMass/comfy_mtb/files/14728853/AP.Workflow.9.0.EA4_nodes_snapshot.json)

**Comment by melMass** [comment]
Thanks for reference:

```sh
╭────┬─────────────────┬───────────────────────────────╮
│  # │     author      │           extension           │
├────┼─────────────────┼───────────────────────────────┤
│  0 │ Acly            │ comfyui-tooling-nodes         │
│  1 │ Acly            │ comfyui-inpaint-nodes         │
│  2 │ BadCafeCode     │ masquerade-nodes-comfyui      │
│  3 │ EllangoK        │ ComfyUI-post-processing-nodes │
│  4 │ Fannovel16      │ comfyui_controlnet_aux        │
│  5 │ Gourieff        │ comfyui-reactor-node          │
│  6 │ Kosinkadink     │ ComfyUI-Advanced-ControlNet   │
│  7 │ Kosinkadink     │ ComfyUI-VideoHelperSuite      │
│  8 │ RockOfFire      │ ComfyUI_Comfyroll_CustomNodes │
│  9 │ Stability-AI    │ stability-ComfyUI-nodes       │
│ 10 │ TinyTerra       │ ComfyUI_tinyterraNodes        │
│ 11 │ WASasquatch     │ was-node-suite-comfyui        │
│ 12 │ Zuellni         │ ComfyUI-PickScore-Nodes       │
│ 13 │ brianfitzgerald │ style_aligned_comfy           │
│ 14 │ chrisgoringe    │ cg-image-picker               │
│ 15 │ chrisgoringe    │ cg-custom-core.git            │
│ 16 │ comfyanonymous  │ ComfyUI_experiments           │
│ 17 │ cubiq           │ ComfyUI_FaceAnalysis          │
│ 18 │ cubiq           │ ComfyUI_InstantID             │
│ 19 │ cubiq           │ ComfyUI_essentials            │
│ 20 │ cubiq           │ ComfyUI_IPAdapter_plus        │
│ 21 │ dnl13           │ ComfyUI-dnl13-seg             │
│ 22 │ dnl13           │ comfyui_segment_anything      │
│ 23 │ failfa-st       │ failfast-comfyui-extensions   │
│ 24 │ glibsonoran     │ Plush-for-ComfyUI             │
│ 25 │ jags111         │ efficiency-nodes-comfyui      │
│ 26 │ jitcoder        │ lora-info                     │
│ 27 │ kijai           │ ComfyUI-KJNodes               │
│ 28 │ kijai           │ ComfyUI-DDColor               │
│ 29 │ kijai           │ ComfyUI-moondream             │
│ 30 │ kijai           │ ComfyUI-CCSR                  │
│ 31 │ kijai           │ ComfyUI-SUPIR                 │
│ 32 │ ltdrdata        │ ComfyUI-Manager.git           │
│ 33 │ ltdrdata        │ ComfyUI-Impact-Pack.git       │
│ 34 │ ltdrdata        │ ComfyUI-Inspire-Pack          │
│ 35 │ martijnat       │ comfyui-previewlatent         │
│ 36 │ melMass         │ comfy_mtb                     │
│ 37 │ pythongosssss   │ ComfyUI-Custom-Scripts        │
│ 38 │ receyuki        │ comfyui-prompt-reader-node    │
│ 39 │ rgthree         │ rgthree-comfy                 │
│ 40 │ shiimizu        │ ComfyUI-TiledDiffusion        │
│ 41 │ tzwm            │ comfyui-browser               │
├────┼─────────────────┼───────────────────────────────┤
│  # │     author      │           extension           │
╰────┴─────────────────┴───────────────────────────────╯

```

I'll do some more testing today and let you know.

**Comment by alessandroperilli** [comment]
Thank you. You can eliminate n0 and n9 from the list. I updated the json accordingly.

**Comment by melMass** [comment]
Here is the diff from me if you want to investigate on your side in the meantime.
The following list is the ones I don't have, more than I expected but not a lot that act on web things. Tinyterra has caused many issues in the past and I haven't tried in a long time I'll start with that:

```sh
╭────┬─────────────────┬───────────────────────────────╮
│  # │     author      │           extension           │
├────┼─────────────────┼───────────────────────────────┤
│  0 │ Acly            │ comfyui-tooling-nodes         │
│  1 │ BadCafeCode     │ masquerade-nodes-comfyui      │
│  2 │ EllangoK        │ ComfyUI-post-processing-nodes │
│  3 │ Gourieff        │ comfyui-reactor-node          │
│  4 │ TinyTerra       │ ComfyUI_tinyterraNodes        │
│  5 │ Zuellni         │ ComfyUI-PickScore-Nodes       │
│  6 │ brianfitzgerald │ style_aligned_comfy           │
│  7 │ chrisgoringe    │ cg-image-picker               │
│  8 │ chrisgoringe    │ cg-custom-core.git            │
│  9 │ cubiq           │ ComfyUI_FaceAnalysis          │
│ 10 │ cubiq           │ ComfyUI_InstantID             │
│ 11 │ dnl13           │ ComfyUI-dnl13-seg             │
│ 12 │ dnl13           │ comfyui_segment_anything      │
│ 13 │ failfa-st       │ failfast-comfyui-extensions   │
│ 14 │ glibsonoran     │ Plush-for-ComfyUI             │
│ 15 │ jitcoder        │ lora-info                     │
│ 16 │ kijai           │ ComfyUI-DDColor               │
│ 17 │ kijai           │ ComfyUI-moondream             │
│ 18 │ ltdrdata        │ ComfyUI-Inspire-Pack          │
│ 19 │ martijnat       │ comfyui-previewlatent         │
│ 20 │ receyuki        │ comfyui-prompt-reader-node    │
│ 21 │ tzwm            │ comfyui-browser               │
╰────┴─────────────────┴───────────────────────────────╯

```

**Comment by alessandroperilli** [comment]
ttN was my prime suspect for the exact reason you mentioned, but it's not it. And it's not LoraInfo at n15 either (another prime suspect).
