### ISSUE TITLE
[bug] XSS use of ace.min.js

### ISSUE THREAD

**Issue by daniel-lewis-ab** [melMass/comfy_mtb#166]
### Describe the bug

Hi, I'm working on a project that involves examining a bunch of the ComfyUI nodes' JS.

    In comfyui_shared.js:417 and note_plus.js you use a loadScript() to load ace.min.js into the script. NotePlus node wasn't visible in utils. I've disabled the remote script import for our purposes but just wanted to point out the state it was found in. This may be an out of date version issue that's already been fixed in your main? Regardless, the external path thing is something that would probably be best localized for security reasons for most uses.

    web/extern/shodown.js being deleted seems to not cause any errors at a cursory glance, and I'm not sure why it's there? Solving this riddle is flagged as one of my remaining issues before we can include your node in a large project.

### Reproduction

The affected code is note_plus.js

### Expected behavior

I would hope to see the ace.min.js call either localized to directory or removed altogether to prevent the possibility of the remote server being used as a vector of attack to other people's machines/browser experience/servers.

### Operating System

Linux

### Comfy Mode

Other (online services, containers etc..)

**Comment by melMass** [comment]
Good point yes it makes sense since I do for other externals.
Ace is used solely for the editing part of note plus

**Comment by daniel-lewis-ab** [comment]
https://github.com/melMass/comfy_mtb/pull/167

**Comment by melMass** [comment]
> #167
> 
> As mentioned, test before pulling.

Thanks, given the nature of the PR (huge minified code..) I will do it myself.
I think it's also missing all the utility files (from cdn they are linked properly)
I will quickly look into it now, and if there are no blockers it should be solved soon

**Comment by daniel-lewis-ab** [comment]
Fantastic.

**Comment by melMass** [comment]
It was way more involving than planned since comfy preloads all the scripts in the web folder.
The trick was to add an extra static path to the server!
Let me know if it solves your security concerns

**Comment by daniel-lewis-ab** [comment]
Yeah, that should work.  Now it isn't technically XSS exposed, and if we
scan the file it'll tell us what we need to know.
