### ISSUE TITLE
[bug] Color picker not working

### ISSUE THREAD

**Issue by jervenclark** [melMass/comfy_mtb#170]
### Describe the bug

Hi! I updated my custom nodes today and the latest commit to main seems to break the color picker. 
I already tried cloning directly and installing from comfy manager, but still no luck.

![image](https://github.com/melMass/comfy_mtb/assets/8236178/6c9aaf41-9fd4-4ca6-a3b0-396a032649cf)
![Screenshot from 2024-04-27 10-07-32](https://github.com/melMass/comfy_mtb/assets/8236178/40c4490f-712c-4da2-baa9-63e9914721ab)

It can't find some of the js scripts.
```
import { NumberInputWidget } from './numberInput.js'
```

Reverting to an old commit works.

### Operating System

Linux

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

**Comment by melMass** [comment]
Thanks a lot for the report! It's indeed an untracked file I forgot to add, fixed in 76f365b5eee165c76f3da7d2e3950786685bc08b

Let me know if it solved it

**Comment by jervenclark** [comment]
Thanks for the prompt fix. I really appreciate your custom node.
