### ISSUE TITLE
[bug] Float to Floats does not load

### ISSUE THREAD

**Issue by Davikar** [melMass/comfy_mtb#171]
### Describe the bug

After updating to the latest version one of the new nodes wont load.
If I try to load Float to Floats from the list, nothing happens.
The other one, Floats to Float does seem to work normally.
Also, as a side effect it seems I have to replace all the old number to float nodes...

### Reproduction

1. Try to load Float to Floats either via menu or search box.
2. ...

### Expected behavior

1. Try to load Float to Floats either via menu or search box.
2. The node appears.

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks for the report, I was missing the "options" required for FLOAT.
I will change it now to "force_input" since it will always be that.
