### ISSUE TITLE
[bug] int to number broken

### ISSUE THREAD

**Issue by ricperry** [melMass/comfy_mtb#172]
### Describe the bug

Prior workflows that used int to number node were working. Now ComfyUI can't find the node.

![Screenshot from 2024-05-01 20-08-36](https://github.com/melMass/comfy_mtb/assets/34995372/d17065fc-022c-4fb1-b885-4315df9ea0fa)

![image](https://github.com/melMass/comfy_mtb/assets/34995372/1fa2ba8e-6be9-494e-ba71-1c8dc76544b3)

### Operating System

Linux

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Console output

```sh
[comfy_mtb] | INFO -> loaded 71 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://None:8188/mtb if you want more information.

got prompt
Failed to validate prompt for output 181:
* Any To String (mtb) 179:
  - Return type mismatch between linked nodes: input, INT != *
Output will be ignored
Failed to validate prompt for output 180:
* Any To String (mtb) 178:
  - Return type mismatch between linked nodes: input, INT != *
Output will be ignored
```

### Additional context

There are 2 nodes that fail to load, but neither one is int to number, while int to number is just missing completely now.

**Comment by melMass** [comment]
Thanks for the report, I removed them thinking they weren't used, seems like I was wrong. I'll add them again
