### ISSUE TITLE
[bug] Note Plus box is empty when exporting workflow as png

### ISSUE THREAD

**Issue by audioscavenger** [melMass/comfy_mtb#174]
### Describe the bug

Note Plus does not print when exporting workflow as png, it's blank

### Reproduction

1. add note
2. add some stuff ## title etc
3. right click workflow image > export >png
4. note plus is blank
![image](https://github.com/melMass/comfy_mtb/assets/3853962/7993f360-82c7-4166-969b-12c6f0707c0b)

### Expected behavior

note content is visible

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Additional context

i have like 50 cutom nodes and zero errors on load

**Comment by melMass** [comment]
I'm guessing you are referring to pythongosss workflow image extension? 

It only supports canvas element and would require a whole rewrite of note+, it's maybe easier to add DOM support to workflow image, I briefly asked pythongosss a few weeks ago but don't recall their answer sorry
