### ISSUE TITLE
[bug] batch node cannot to connect the other customer node

### ISSUE THREAD

**Issue by cardenluo** [melMass/comfy_mtb#179]
### Describe the bug

![image](https://github.com/melMass/comfy_mtb/assets/133877069/4cfcfae6-2422-49a3-b29b-cf19ec933feb)
it maybe Float ?  it can not  to connect the other node . 

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
For now, I decided to use a dedicated type in mtb, I don't get the initial logic of using lists typed as FLOAT since it will connect but won't work with 90% of the nodes.

For bridging between there is this node: https://github.com/melMass/comfy_mtb/wiki/nodes-floats-to-float

**Comment by cardenluo** [comment]
thanks , I find  the node

**Comment by melMass** [comment]
> thanks , I find the node

Cool! I plan to document it all a bit better soon, and I have a large list of examples I'm cleaning to go along the docs
