### ISSUE TITLE
[bug] CURVE(mtb) node

### ISSUE THREAD

**Issue by liulsg** [melMass/comfy_mtb#183]
### Describe the bug

When the curve(MTB) node is called, the entire page enters a stuck state, all operations are invalid, and comfyui is still invalid even after restarting.

### Reproduction

How to reproduce: You don't need anything else, just put the curve node on the canvas

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Additional context

Any canvas, with or without workflow

**Comment by melMass** [comment]
Thanks for the report!

Curve is still a bit WIP but it should be functional. [Kijai](https://github.com/kijai/ComfyUI-KJNodes) made a more feature rich alternative (Spline Editor).
For mtb curve I want to use either bspline (auto interpolated) or bezier but keep it simple.

Can you check the web console for errors? What you describe usually happens on unhandled frontend errors and the console should provide more info

**Comment by liulsg** [comment]
sidebar_node.js:886 minimized
sidebar_node.js:886 minimized
sidebar_node.js:886 minimized
sidebar_node.js:886 minimized
curve_widget.js:92 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at CurveWidget.draw (curve_widget.js:92:32)
    at LGraphCanvas.drawNodeWidgets (litegraph.core.js:9977:27)
    at LGraphCanvas.drawNodeWidgets (main.js:76:34)
    at LGraphCanvas.drawNode (litegraph.core.js:8776:22)
    at LGraphCanvas.drawNode (label.js:134:27)
    at LGraphCanvas.drawNode (snapToGrid.js:86:24)
    at snapToGrid.js:39:43
    at wrapCallInSettingCheck (snapToGrid.js:16:9)
    at LGraphCanvas.drawNode (snapToGrid.js:39:5)
draw @ curve_widget.js:92
LGraphCanvas.drawNodeWidgets @ litegraph.core.js:9977
LGraphCanvas.drawNodeWidgets @ main.js:76
LGraphCanvas.drawNode @ litegraph.core.js:8776
LGraphCanvas.drawNode @ label.js:134
LGraphCanvas.drawNode @ snapToGrid.js:86
（anonymous） @ snapToGrid.js:39
wrapCallInSettingCheck @ snapToGrid.js:16
LGraphCanvas.drawNode @ snapToGrid.js:39
LGraphCanvas.drawNode @ app.js:1290
LGraphCanvas.drawNode @ use_everywhere.js:186
LGraphCanvas.drawFrontCanvas @ litegraph.core.js:7827
LGraphCanvas.draw @ litegraph.core.js:7742
renderFrame @ litegraph.core.js:5809
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
requestAnimationFrame（asynchronous）
renderFrame @ litegraph.core.js:5814
sidebar_node.js:886 minimized


browser：Google Chrome
If you need any more information, you can leave a message. I'll try my best to provide it.

**Comment by melMass** [comment]
Should be good, don't hesitate to comment/reopen if not
