### ISSUE TITLE
[feat] Add support for RGBA images in FaceSwap

### ISSUE THREAD

**Issue by haomole** [melMass/comfy_mtb#187]
### Describe the problem

I would like to know where I can change the image background opacity, thank you

### Describe the solution you'd like

I would like to know where I can change the image background opacity, thank you

**Comment by haomole** [comment]
I may have found it. It's located in the swap_face function in ComfyUI\custom_nodes\comfy_mtb\nodes\faceswap.py. But I'm not familiar with python programming, so can you help me fix it? The application scenario is that target_img contains transparent channels, result_image will not contain the transparent background image in target_img original image, if possible, thank you very much!

**Comment by melMass** [comment]
Hi,

I re-read it multiple times but don't understand your issue or goal.
What background are you trying to change?

**Comment by haomole** [comment]
Thank you for your reply. Maybe my software has a problem.
I want to give you an example of what I mean that you might get:

**Comment by haomole** [comment]
Thank you for your reply. Maybe my software has a problem.
I want to give you an example of what I mean that you might get:
![img](https://github.com/melMass/comfy_mtb/assets/143379961/80bdd50d-d699-4036-ae1a-a0bec159bd34)

**Comment by melMass** [comment]
Oh I see!
Yes, that shouldn't be an issue to add! 
I will address it tomorrow, I still use these nodes but there is a dedicated node pack for face swapping now with better face restoration: https://github.com/Gourieff/comfyui-reactor-node

**Comment by haomole** [comment]
very thankful！！

**Comment by melMass** [comment]
I just had a look, 
A few things are going on:

- **First**: Comfy's `LoadImage` is outputing RGB in the first slot and mask in the second so you get this:
  ![image](https://github.com/melMass/comfy_mtb/assets/7041726/bd6e0b81-97bb-4950-b434-8102b525bfb6)
  For this you can use my `Image Premultiply` node (I think there is also a native way now):
  ![image](https://github.com/melMass/comfy_mtb/assets/7041726/a20b46df-4af1-4f03-9e16-7bd2f3af62f0)

- **Second**:  the insightface model can't infere RGBA (an image with transparency) so what I did is added a `preserve_alpha` checkbox that will simply reapply the original transparency back. It's not a perfect solution but it should work in most cases!
  ![image](https://github.com/melMass/comfy_mtb/assets/7041726/915c6e34-893b-4f57-b538-755711ce1115)
  ![image](https://github.com/melMass/comfy_mtb/assets/7041726/91f0d88b-692b-4445-8c20-136dfe40d60f)

**Comment by haomole** [comment]
Thanks a lot, I tried to use "Comyui-BRIA_AI-RMBG" to convert the image to RGMA, but it added about 0.5 seconds to the runtime.
![77428c9b-62c0-4ab0-a01e-b5e6a512b16d](https://github.com/melMass/comfy_mtb/assets/143379961/3ea65ce2-a14e-4eb0-bf2c-c746393387c7)

**Comment by melMass** [comment]
@haomole You need to update mtb, here is an example, just replace it with your inputs:

[faceswap_alpha.json](https://github.com/user-attachments/files/16086682/faceswap_alpha.json)

**Comment by haomole** [comment]
Thank you very much, I have downloaded and tested it, and the results are perfect! The only regret is that it takes longer to run.
