### ISSUE TITLE
[bug] Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

### ISSUE THREAD

**Issue by water110** [melMass/comfy_mtb#189]
### Describe the bug

![image](https://github.com/user-attachments/assets/f8d5d4f8-e5a2-4873-bb3d-d248b62fce2d)

It doesn't show any error reason, it just tells that it failed to load, so what can I do to solve the problem?

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by taloniousrex** [comment]
I'm having this issue as well, ComfyUI portable. I had this running earlier but needed to rebuild to accommodate dw pose. Even though there are no errors on Color Correct (mtb) the gamma/contrast, it is no longer working as well, its not effecting the image. This seems like it could be related to a Pytorch/Cuda/Onyx version mismatch with mtb nodes, but I couldn't find versions for these in the dependencies to try to figure out what might work.

Python 3.11.8
Pytorch 2.3.0+cu121
CUDA 12.1
onnxruntime-gpu==1.17.1

**Comment by melMass** [comment]
These nodes are just deprecated that's a warning not an error

**Comment by netdzynr** [comment]
It would be great if your example workflows (1, 2, 6, and 8) could be updated to avoid referencing deprecated nodes. Thanks.

**Comment by melMass** [comment]
See old notice here, I will make it clearer and provide much morer examples for all the nodes: https://github.com/melMass/comfy_mtb/blob/991af4f45ff8c660b2c45466bb219186699170ed/README.md#optional-nodes
