### ISSUE TITLE
[Enhancement Request] FaceSwap Node: Cache faces and face_analyser model

### ISSUE THREAD

**Issue by MoonMoon82** [melMass/comfy_mtb#19]
Hi!

I just saw that the faces (`source_face` and  `target_face`) in function `swap_face` are not being cached.
Also in function `get_face_single` the `face_analyser` model is loaded everytime the node is executed.

I assume it would save some time if the faces and face_analyser model is cached after the `FaceSwap` node is executed.
 (If you agree, please be aware of caching this data in the `FaceSwap` node wouldn't help because it's going to be resetted immediately if any input is changed - so I suggest you to store this cache data in the `LoadFaceSwapModel` node.)

Kind regards

**Comment by melMass** [comment]
Thanks!
Good points! I will look into it

**Comment by melMass** [comment]
@MoonMoon82 This was auto closed by my commit, but it's indeed much faster now! I think there is still a bit of optimization possible but it's much better already! 

I made this to test it out 😅 

**Georges Lucas as Terminator**:
*The player seems to no like it, but you can [click here](https://github.com/melMass/comfy_mtb/assets/7041726/3bf66268-fb90-425f-a5df-fe0f8ac1a9a1) to watch it*
<video width=450 src="https://github.com/melMass/comfy_mtb/assets/7041726/3bf66268-fb90-425f-a5df-fe0f8ac1a9a1"/>

I also updated the [example file](https://github.com/melMass/comfy_mtb/wiki/Examples) to match this update

**Comment by MoonMoon82** [comment]
@melMass This is awesome fast!! Great work!! 
Just a tiny issue: antelopev2.zip and buffalo_m.zip could not been downloaded automatically. I guess these file are taken down. I needed to search the web to download them from a google drive and extract them manually.
