### ISSUE TITLE
[bug] the variable name is error

### ISSUE THREAD

**Issue by allmelgr** [melMass/comfy_mtb#196]
### Describe the bug

catch e but log error

### Operating System

Linux

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
I would need more info

**Comment by allmelgr** [comment]
> I would need more info

const mtb_widgets = {
  name: 'mtb.widgets',


  init: async () => {
    infoLogger('Registering mtb.widgets')
    try {
      const res = await api.fetchApi('/mtb/debug')
      const msg = await res.json()
      if (!window.MTB) {
        window.MTB = {}
      }
      window.MTB.DEBUG = msg.enabled
    } catch (e) {
      console.error('Error:', error)
    }
  },
