### ISSUE TITLE
[bug] Note+ strips html attributes?

### ISSUE THREAD

**Issue by fuzhao119** [melMass/comfy_mtb#198]
### Describe the bug
The target attribute in a `<a>` link is stripped

### Reproduction

This:
```html
<a href="https://xxx" target="_blank"></a>.
```

Is turned into this on save of Note+:
```html
<a href="https://xxx"></a>.
```

### Expected behavior

Not stripping attributes

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by fuzhao119** [comment]
After clicking the SAVE button, <a href="https://xxx" target="_blank"></a> changes to <a href="https://xxx"></a>

**Comment by melMass** [comment]
I think you forgot something. 
I have no idea what you are referring to

**Comment by melMass** [comment]
I guessed what you meant and rewrote the issue

**Comment by melMass** [comment]
This is true for the HTML mode, I will check what makes sense to allow. 
For markdown, `_blank` is the default, so this would do what you want:
```markdown
## Note+
Go here [site](https://www.xxx.com)
```

Markdown is the preferred mode as it should be a superset of HTML in Note+

**Comment by fuzhao119** [comment]
My purpose is to open a window in a new tab, rather than refreshing the current comfyui page

**Comment by fuzhao119** [comment]
![Uploading 微信图片_20240911090532.png…]()

**Comment by fuzhao119** [comment]
@melMass

**Comment by melMass** [comment]
I'm closing it just to do some cleanup.
When #221 will be merged, `_blank` will be the default for `a` tags
