### ISSUE TITLE
[bug] Front-end js causes the BoolToInt node of the ComfyMath plug-in to be unusable

### ISSUE THREAD

**Issue by lldacing** [melMass/comfy_mtb#201]
### Describe the bug

![image](https://github.com/user-attachments/assets/9890c823-a0f0-4581-90e3-80f0be099663)
![image](https://github.com/user-attachments/assets/d9a49bf6-2bf7-4295-af94-9ca0c656a175)

### Operating System

Windows (Default)

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

**Comment by melMass** [comment]
Can you link the ConfyMath node pack? They probably define their custom BOOL type. I was too before we had a builtin BOOLEAN but I think I can juste remove it now

**Comment by melMass** [comment]
Fixed thanks for the report
