### ISSUE TITLE
[bug] the Wiki link in the main README doesn't work

### ISSUE THREAD

**Issue by blepping** [melMass/comfy_mtb#202]
### Describe the bug

the link seems to point into the repo: `https://github.com/melMass/comfy_mtb/blob/main/wiki`
but the Wiki is a separate thing: `https://github.com/melMass/comfy_mtb/wiki`. super simple fix is just to use the absolute link. i'm going to guess it would be easier for you to fix than to deal with a pull.

obviously not much of a problem. oh no, the Wiki link is 404, i guess i'll move my mouse up to the top of the screen and hit the Wiki link there instead!

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks for the report!
