### ISSUE TITLE
[bug] There is no way to open the node+ node for editing.

### ISSUE THREAD

**Issue by lichard001** [melMass/comfy_mtb#205]
### Describe the bug

There is no way to open this node+ node for editing, to realize the effect of webpage jumping, and there is no response to mouse clicks.
<img width="294" alt="12313" src="https://github.com/user-attachments/assets/312e77b2-3f96-4525-80f0-693ca915cda2">

pytorch version: 2.1.2+cu118
xformers version: 0.0.23.post1

or

pytorch version: 2.4.1+cu124
xformers version: 0.0.28

None of them are working properly.

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks for the report, I will investigate later today and report back here.
In the meantime can you tell which browser you are using?

**Comment by lichard001** [comment]
Additional note: I'm using the chorme browser, and the comfyui kernel was updated to v0.2.4 (2024-10-22 14:12:28) If I rollback comfy_mtb to bc41576 (2024-09-29) everything works fine, and if I update it to dbcca15 (2024-10-10) it appears again with the above bug described above.

**Comment by lichard001** [comment]
> Thanks for the report, I will investigate later today and report back here. In the meantime can you tell which browser you are using?

Additional note: I'm using the chorme browser and the comfyui kernel has been updated to v0.2.4 (2024-10-22). If I roll back the kernel to v0.2.2 (2024-09-06), then the use of comfy_mtb returns to normal. The version of comfy_mtb tested above is dbcca15 (2024-10-10).

**Comment by lichard001** [comment]
Also I would like to give feedback on another issue, is there any way to realize that when clicking on a hyperlink, a new window pops up instead of refreshing the current comfyui page.
[https://github.com/melMass/comfy_mtb/issues/198#issue-2507684358](url)

Every time I click the save button, it automatically changes to this result.
<img width="554" alt="Snipaste_2024-10-25_14-11-04" src="https://github.com/user-attachments/assets/a7013c08-5fa5-4a83-a508-446f86c38b65">
<img width="546" alt="Snipaste_2024-10-25_14-11-44" src="https://github.com/user-attachments/assets/abd56848-7c86-42c9-9460-4d25e800fa6b">

Thanks for all you do, it's a great tool and thanks for your help!

**Comment by melMass** [comment]
It's probably due to a front end update I did not follow! 

Regarding hyperlinks it's been asked before and I see the point! I think the easiest for now is probably to default to opening hyperlinks in a new tab, I will change that too

**Comment by melMass** [comment]
I will address all these today!

**Comment by NOTlinnkoln** [comment]
same issue for note+ cannot edit it

**Comment by NOTlinnkoln** [comment]
Oh, just find something interesting  
it WORKS but in really tiny area 
<img width="457" alt="image" src="https://github.com/user-attachments/assets/933dde56-0668-4aa3-8d2f-46aff093a7fc">

**Comment by lichard001** [comment]
> Oh, just find something interesting it WORKS but in really tiny area <img alt="image" width="457" src="https://private-user-images.githubusercontent.com/179947730/382295043-933dde56-0668-4aa3-8d2f-46aff093a7fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0NzA0MjksIm5iZiI6MTczMTQ3MDEyOSwicGF0aCI6Ii8xNzk5NDc3MzAvMzgyMjk1MDQzLTkzM2RkZTU2LTA2NjgtNGFhMy04ZDJmLTQ2YWZmMDkzYTdmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExM1QwMzU1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmFlZjlmNjEzOGU0NDY0YmEzYTU2NDY4N2MyOWE2MjcyMzFhYjUxOWEyZDdjMmZlZTcxM2VlYjA0ZGVlNDYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iWcAn2YZROpe3J8eANzsdR86AIs5DPRgWSfVbVBbOpc">

genius
