### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by Vbaethon** [melMass/comfy_mtb#206]
### Describe the bug

On macOS M1 Max, while using ComfyUI with the MTB plugin, several nodes (like FaceSwap, LoadFaceAnalysisModel, LoadFaceSwapModel) fail to load. The issue seems to stem from incompatible dependencies, especially when using Python 3.10.15, resulting in version conflicts.
![CleanShot 2024-10-25 at 01 58 06@2x](https://github.com/user-attachments/assets/f3d18319-c03f-4db1-9309-6ea234a5c0d0)

### Reproduction

conda envs
python 3.10.15
tensorflow just 2.16.2
macOS
m1 max

### Operating System

Mac

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
This is "expected" especially on macos but I will add back the notice that was here: https://github.com/melMass/comfy_mtb/blob/991af4f45ff8c660b2c45466bb219186699170ed/README.md#optional-nodes
