### ISSUE TITLE
[feat] Ability to use and select other sampling algorithms for Transform Image node

### ISSUE THREAD

**Issue by nathanshipley** [melMass/comfy_mtb#209]
### Describe the problem

When I use Transform Image to scale and transform an image, it appears to be using Nearest Neighbor sampling.  Results are blocky.  Is it possible to enable other sampling algos?  Bicubic, Lanczos, etc?

### Describe the solution you'd like

A drop down that selects sampling algorithm for transform.

**Comment by melMass** [comment]
Hi Nathan, 
Yes good point I will add the common on to both transform image nodes
