### ISSUE TITLE
[bug]  I/O Sidebar doesn't work with custom `input-directory` / `output-directory`

### ISSUE THREAD

**Issue by ElSuccerro** [melMass/comfy_mtb#219]
### Describe the bug

Sidebar MTB: Browse input and out directories does not work

### Reproduction

If i click in the sidebar MTB: Browse input and out directories

### Expected behavior

A lsit of the pics in input and output directories

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
Error handling request
Traceback (most recent call last):
  File "A:\ComfyUI_2.41\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 479, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\ComfyUI\server.py", line 62, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\ComfyUI\server.py", line 140, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\ComfyUI\server.py", line 74, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 550, in do_action
    return await endpoint.do_action(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 166, in do_action
    result = method(*args) if isinstance(args, list) else method(args)
             ^^^^^^^^^^^^^
  File "A:\ComfyUI_2.41\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 93, in ACTIONS_getUserImages
    imgs = {
           ^
  File "A:\ComfyUI_2.41\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 100, in <dictcomp>
    if offset <= i < offset + count
                     ~~~~~~~^~~~~~~
```

**Comment by melMass** [comment]
Thanks for the report but I think your cropped the important part (just below that last line)
My guess is that one of the folder is probably empty. With more info it should be an easy fix

**Comment by ElSuccerro** [comment]
Thank you for your feedback. I have checked that if I check “Enable Debug (py and js)” the error is gone and if images are directly in the input and output folders they are now also displayed.
But I use the startup arguments: 
--input-directory “H:\AI_Pics\ComfyUI\input” 
--output-directory “H:\AI_Pics\ComfyUI\Output_New”
Then no images are displayed but only the default error.png
Will this be changed?

Translated with DeepL.com (free version)

**Comment by melMass** [comment]
Oh I see! 

> Will this be changed?

Yes definitely, it should work as you expect here. I'll check what's going on and close this issue when fixed

**Comment by melMass** [comment]
It should be fixed, if not i'll re-open it!

**Comment by ElSuccerro** [comment]
Thanks for the quick repair. Now everything works as it should!

**Comment by melMass** [comment]
> However, I have many subdirectories in my output directory. Could this be a problem?

Currently it's expected, I have all in place to support it but I'm not sure how to display subdirs (either dump all in a common root list, or maybe add extra menu like `output (<name-of-subdir>)` etc... ) ideally something configurable.
Same for pagination I have part of the logic in place but it's not fully implemented so for now I set the default to fetch `1000` images per category.

I'll open a new issue to track that! If you have ideas on how it should behave don't hesitate to comment there
