### ISSUE TITLE
ComfyUI Simlink Failure[bug] 

### ISSUE THREAD

**Issue by Piscabo** [melMass/comfy_mtb#26]
### Describe the bug

Log level: 20
[comfy_mtb] | ERROR -> Failed to create symlink to C:\AI_Files\ComfyUI_windows_portable\ComfyUI\web\extensions\mtb. Please copy the folder manually.

### Reproduction

1. Install MTB Node and Controlnet
2. Symlink failure when the server starts
3. Copy mtb to ComfyUI_windows_portable\ComfyUI\web\extensions
4. Restart the server, but symlink still fails

### Expected behavior

After copying the full folder to the suggested position no error should occur.

### Platform and versions

```sh
Windows 11
ComfyUI Standalone "https://github.com/comfyanonymous/ComfyUI/releases"
```

### Console output

```sh
Log level: 20
[comfy_mtb] | ERROR -> Failed to create symlink to C:\AI_Files\ComfyUI_windows_portable\ComfyUI\web\extensions\mtb. Please copy the folder manually.
[comfy_mtb] | ERROR -> Some nodes failed to load:
        Failed to import faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import fun because ModuleNotFoundError: No module named 'qrcode'
        Failed to import image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/melMass/comfy_mtb/issues)
```

**Comment by melMass** [comment]
Thanks for the report.

Can you confirm the path is where you did copy the web folder manually?

This is actually optional, I will replace error by a warning to avoid confusion.

The other errors though indicate that the dependencies are not installed for these specific nodes. If you don't need them you can just ignore it, I made it so that part of the extension can fail to register.

**Comment by Piscabo** [comment]
> ```shell
> ComfyUI\web\extensions\
> ```

![image](https://github.com/melMass/comfy_mtb/assets/123719842/c4dcaa45-439c-40d3-9c6f-d87721f651ef)
![image](https://github.com/melMass/comfy_mtb/assets/123719842/4debbe50-5893-4fd1-929a-d26f6871713f)
And as soon as roop is installed, this happens?
![image](https://github.com/melMass/comfy_mtb/assets/123719842/a80f333d-3b35-4bf4-b9d9-9c48cd20b96f)

**Comment by melMass** [comment]
So the first screen you must copy the "web" folder to "mtb" not "comfy_mtb" inside the web extensions, I'll make that more obvious for when symlink fails.

The second error is probably due to another extension that rely on an older version of onnx, I believe mtb uses the most recent one 1.15.1, updating onnx might break that said extension...

It would be great to know which extension is causing this issue if you manage to find

**Comment by DarkCoverUnleashed** [comment]
Failed to import faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import fun because ModuleNotFoundError: No module named 'qrcode'
        Failed to import image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

How do I install dependencies for these 4 . I have followed the install dependencies guide according to INSTALL.md .But still show this error. 
thanks in advance

**Comment by Piscabo** [comment]
> ```
>     Failed to import faceenhance because ModuleNotFoundError: No module named 'basicsr'
>     Failed to import faceswap because ModuleNotFoundError: No module named 'insightface'
>     Failed to import fun because ModuleNotFoundError: No module named 'qrcode'
>     Failed to import image_interpolation because ModuleNotFoundError: No module named 'tensorflow'
> ```
> 
> How do I install dependencies for these 4 . I have followed the install dependencies guide according to INSTALL.md .But still show this error. thanks in advance

Just run the MTB requirements install from the python_embbed: (** where you have it installed...)
C:\**\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -r requirements.txt

**Comment by melMass** [comment]
Exact! I'm taking a bit more time for the next release as I very recently discovered the manager which will be the recommended way to install mtb moving forward, I just need to tune a few things to take various setups into account. That should help with the install issues... 90% of the issues are about that 😅 , I'd rather dedicate time on the nodes

**Comment by Piscabo** [comment]
> Exact! I'm taking a bit more time for the next release as I very recently discovered the manager which will be the recommended way to install mtb moving forward, I just need to tune a few things to take various setups into account. That should help with the install issues... 90% of the issues are about that 😅 , I'd rather dedicate time on the nodes

Wish I could help... but too dumb for that. But I'm a good tester... :-)
I have this error for the faceswap setup. (what model should I use?)
Error occurred when executing Load Face Swap Model (mtb):

[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\AI_Files\ComfyUI_windows_portable\ComfyUI\models\insightface\detection_mobilenet0.25_Final.pth failed:Protobuf parsing failed.

**Comment by melMass** [comment]
For now only the `inswapper_128.onnx` model can be loaded from the loadModel, I should probably omit the detection models from this list, they are used by the faceswap node itself but not exposed, they will probably be used in a dedicated load node as requested in #19
