### ISSUE TITLE
Install with Manger creates a duplicate[bug] 

### ISSUE THREAD

**Issue by Piscabo** [melMass/comfy_mtb#45]
### Describe the bug

A custom nodes folder is created within the comfy_mtb, with another instance of mtb?
![image](https://github.com/melMass/comfy_mtb/assets/123719842/1549f7ad-8880-4d7e-a553-030a53eebd31)

### Reproduction

1. Mtb Install through manager
2. duplicate mt nodes created

### Expected behavior

A correct install without duplicated folders?

### Platform and versions

```sh
windows 11
comfyui with venv
```

### Additional context

![image](https://github.com/melMass/comfy_mtb/assets/123719842/25cc50d7-f085-4251-9297-c42e3f963f95)

**Comment by melMass** [comment]
Thanks for the report, I think I know why, my install script misunderstand the mode it's run in and assume pipe which is wrong, so it starts a full install from scratch (cloning the repo etc) ... 
I will remove this as it's not working the same across platform and lead to these kind of bugs.
I introduced this bug when I fixed the embed test pipeline I think https://github.com/melMass/comfy_mtb/actions/runs/5721443310/job/15503040283

**Comment by melMass** [comment]
Should be fixed by https://github.com/melMass/comfy_mtb/commit/b854a302ce4708d2ad2dac249860308dbdcae5a6

But I will test it further before closing this issue :)

**Comment by melMass** [comment]
Thanks again
