### ISSUE TITLE
[Feature Request] Separate FaceSwap Model loading

### ISSUE THREAD

**Issue by MoonMoon82** [melMass/comfy_mtb#5]
Hi! Everythings working fine, but I guess there could be an enhancement regarding performance of the FaceSwap node:

Everytime the IMAGE input changes, the FaceSwap node loads up the faceswap model again:
Log:
`[comfy_mtb.nodes.faceswap] | INFO -> Loading model C:\SD\ComfyUI_windows_portable\ComfyUI\models\insightface\inswapper_128.onnx`

This could be improved by separating the FaceSwap node into two nodes - one for loading of the model, the second for applying the model.
I guess it was already tried to be implemented by the "getFaceSwapModel" function, but unfortunately the whole node is being reinitialized if an node input changes.

**Comment by melMass** [comment]
It should already use the cached one on second run does it not on your end?
