### ISSUE TITLE
Totally unclear as to Load Image sequence[bug] 

### ISSUE THREAD

**Issue by AIMusicExperiment** [melMass/comfy_mtb#51]
### Describe the bug

You have a suite of amazing nodes with almost no instructions for use. I am trying to use "Load Image Sequence (MTB)" with little success.  The problem is in the "path input." If I give it the full path to a given image, it will load that image over and over again, regardless of the current frame setting. I have the images named the same with a "( )" with a number in the parentheses. I've tried wildcards in the path etc., but unless I point to the actual file I get an error. How on God's green earth do I get this to load sequence of images? (As the name implies)   

### Reproduction

1. Add Load Image Sequence (MTB) Node
2. set the absolute path to an image with in a folder of sequential images
3. press Queue Prompt 
4. It loads the targeted image
5. increase the frame count by one 
6. press Queue Prompt 
7.  if loads the firs image not the second
8. Run screaming down the hall way because you will never get this stupid workflow to work.
9. Make an issue on melMass' Git Hub and pray for a quick answer

### Expected behavior

Well one would hope it would do what the name implies. . .

### Platform and versions

```sh
-Windows 10
-ComfyUIBackend on Stable Swarm, but same issue on ComfyUI portable
-Everything is updated to current version as of right now.
```

### Additional context

I really Love you nodes! At least the ones that I can get to work.  Please offer some instruction for you suite! Also I am a YouTube creator, if you will help me get these figured out I will happily post tutorials! -Ava

**Comment by melMass** [comment]
Hi Thanks for the report!

This node will get an improvement soon as its use is a bit opiniated for now.
It can work in two ways: to pick an image from an image sequence on disk, so let's say you have:

```
/path/to/imgA_001.png
/path/to/imgA_002.png
/path/to/imgA_003.png
/path/to/imgA_004.png
```


You could use `/path/to/imgA_###.png` in the path field, and plug a primitive set to increment (or double click the input) and run a queue of 4 items. If I get you right this is what you tried that always returned the image, I'll test it further and provide a workflow later today: 
<p align=center>
<img src="https://github.com/melMass/comfy_mtb/assets/7041726/c661f0e3-7276-42f2-88a7-4e77eb0a7862"/>
</p>


The second mode is almost the same but you set `current_frame` to -1 and it will load all the frames in a batch:
<p align=center>
<img src="https://github.com/melMass/comfy_mtb/assets/7041726/171e10d4-5e6a-41fe-b4c1-89e93cc2e9bf"/>
</p>

**Comment by AIMusicExperiment** [comment]
You saved the day! This works perfectly. Thanks!

**Comment by melMass** [comment]
Perfect, and regarding documentation,  it's in the work, but I'm also figuring out which node to keep improving on as I sometime found better and already adopted extension / node I did not know about initially but the focus will mainly be "animation" tools

**Comment by AIMusicExperiment** [comment]
Animation tools would be amazing! Until recently I used A1111 only and have
just recently discovered Compyui. The only thing that CompyUI can't do for
me now is the stuff in Deforum. I use hybrid video a lot! I am right now
trying to come up with work flows that will emulate that in CompyUi.  It is
a very complicated extension, so it needs a lot of nodes. . .

**Comment by Eagle07-Sudo** [comment]
Thanks! It would be easier if we could use an external path and pick a range of images from the sequence.

**Comment by curlysasha** [comment]
its not working( 
always use first image, when i`m changing frame number
![image](https://github.com/melMass/comfy_mtb/assets/116119767/70114ddc-509e-4d96-be71-c0b4d293e90c)

**Comment by melMass** [comment]
@curlysasha I recommend [VHS](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite) now, they took a few mtb nodes but enhanced them a lot. That said it still works fine:

![seq](https://github.com/melMass/comfy_mtb/assets/7041726/74845083-09bd-47d9-81c4-4b8e06c9bdea)

**Comment by curlysasha** [comment]
> @curlysasha I recommend [VHS](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite) now, they took a few mtb nodes but enhanced them a lot. That said it still works fine:
> 
> ![seq](https://private-user-images.githubusercontent.com/7041726/315944966-74845083-09bd-47d9-81c4-4b8e06c9bdea.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc0MDQsIm5iZiI6MTcxMTA5NzEwNCwicGF0aCI6Ii83MDQxNzI2LzMxNTk0NDk2Ni03NDg0NTA4My0wOWJkLTQ3ZDktODFjNC00YjhlMDZjOWJkZWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDg0NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhiMTkxZjhkZmQwMDE2ODRlZGNhZjhlYjk2ZTUyM2I0NjJhOGYyOGM4NTZmNWJmYWIxNTlhNzkzN2FkNTZhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wBg1q6uOQv1g3cwPon3d4b6eCUcjVApwXfd_6nL1bok) [ ![seq](https://private-user-images.githubusercontent.com/7041726/315944966-74845083-09bd-47d9-81c4-4b8e06c9bdea.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc0MDQsIm5iZiI6MTcxMTA5NzEwNCwicGF0aCI6Ii83MDQxNzI2LzMxNTk0NDk2Ni03NDg0NTA4My0wOWJkLTQ3ZDktODFjNC00YjhlMDZjOWJkZWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDg0NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhiMTkxZjhkZmQwMDE2ODRlZGNhZjhlYjk2ZTUyM2I0NjJhOGYyOGM4NTZmNWJmYWIxNTlhNzkzN2FkNTZhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wBg1q6uOQv1g3cwPon3d4b6eCUcjVApwXfd_6nL1bok) ](https://private-user-images.githubusercontent.com/7041726/315944966-74845083-09bd-47d9-81c4-4b8e06c9bdea.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc0MDQsIm5iZiI6MTcxMTA5NzEwNCwicGF0aCI6Ii83MDQxNzI2LzMxNTk0NDk2Ni03NDg0NTA4My0wOWJkLTQ3ZDktODFjNC00YjhlMDZjOWJkZWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDg0NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhiMTkxZjhkZmQwMDE2ODRlZGNhZjhlYjk2ZTUyM2I0NjJhOGYyOGM4NTZmNWJmYWIxNTlhNzkzN2FkNTZhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wBg1q6uOQv1g3cwPon3d4b6eCUcjVApwXfd_6nL1bok) [ ](https://private-user-images.githubusercontent.com/7041726/315944966-74845083-09bd-47d9-81c4-4b8e06c9bdea.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTc0MDQsIm5iZiI6MTcxMTA5NzEwNCwicGF0aCI6Ii83MDQxNzI2LzMxNTk0NDk2Ni03NDg0NTA4My0wOWJkLTQ3ZDktODFjNC00YjhlMDZjOWJkZWEuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjJUMDg0NTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhiMTkxZjhkZmQwMDE2ODRlZGNhZjhlYjk2ZTUyM2I0NjJhOGYyOGM4NTZmNWJmYWIxNTlhNzkzN2FkNTZhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wBg1q6uOQv1g3cwPon3d4b6eCUcjVApwXfd_6nL1bok)

They have a lot of errors with dimensions, only nodes from inspire pack working good for me

**Comment by melMass** [comment]
@curlysasha Your images have various dimensions in your folder?

I'm going to open a dedicated issue to rework this node a bit
