### ISSUE TITLE
[bug]: model links are broken

### ISSUE THREAD

**Issue by rethink-studios** [melMass/comfy_mtb#55]
### Describe the bug

Working with MTB, and sent a prompt.
Certain paths to models are working, others are not. It seems deepinsight changed their "releases" directory.

### Reproduction

 https://github.com/deepinsight/insightface/releases/download/v0.7/antelopev2.zip  does not work

### Expected behavior

New paths are here?

https://github.com/deepinsight/insightface/releases

### Platform and versions

```sh
Windows 11
```

**Comment by melMass** [comment]
Hi,

Yes I should probably do it myself, for now it relies on insightface which have those broken links (https://github.com/deepinsight/insightface/blob/00f98ef7331d41c9ce7c54a306fcd228106874c7/python-package/insightface/utils/storage.py#L7-L25)
