### ISSUE TITLE
[feat] increase number of samples

### ISSUE THREAD

**Issue by rethink-studios** [melMass/comfy_mtb#56]
### Describe the problem

Your implementation is very fast, but I wonder if image quality suffers.
Take a look at this video:

https://www.dropbox.com/s/xdiwyfmv29szo6h/MTB_LowRes_Output.mp4?dl=0

### Describe the solution you'd like

I'd love to increase the number of samples, so that images are crisp and clean

### Alternatives considered

Is it possible to add a parameter that increases the number of samples?
Or, am I off target as to how the script works?

**Comment by melMass** [comment]
The thing I discovered while adapting the implementation to Comfy is that inswapper is done at 128px... So the direct output looks bad... That's why there is face restore nodes, they are mainly meant to work with faceswap I don't really use them otherwise, you can check and example of the chain it's the first example here: https://github.com/melMass/comfy_mtb/wiki/Examples

**Comment by melMass** [comment]
I'm going to close this issue but feel free to comment if still not resolved, however not that for face restoration these nodes might give better results for face restoration: https://civitai.com/models/24690/comfyui-facerestore-node

**Comment by rethink-studios** [comment]
Apologies!
I've been playing with the script all weekend, and YES I'm using the upscaler. 
Works well, minus artifacts at the borders:

![image](https://github.com/melMass/comfy_mtb/assets/60104539/19ad8e7d-b615-424b-9015-511d69c727f1)


I know this has been discussed in another thread, but is it possible to add a crop factor parameter, much like in FaceDetailer, to clean up the edges for better image integration?

At this point, to remove, I'll re-encode the image and add a touch of denoise, but that process pushes the image too far away from the desired look:

![image](https://github.com/melMass/comfy_mtb/assets/60104539/cc0af715-19b5-478e-bb13-39f95e372902)


Thoughts?

Getting close!!
Thanks for the hard work!
