### ISSUE TITLE
Wrong path in face enhance model load [bug] 

### ISSUE THREAD

**Issue by Patronogenesys** [melMass/comfy_mtb#57]
### Describe the bug

By default node can't load models. I found a mistake in node file.

Required change in file ComfyUI/custom_nodes/comfy_mtb/nodes/faceenhance.py 
![image](https://github.com/melMass/comfy_mtb/assets/73036922/d074cf71-2f2e-401a-a2e0-23e82d3fc4a5)

### Reproduction

Add node Load Face Enhance Model (mtb)
Try to choose model

### Platform and versions

```sh
Collab ComfyUI
```

**Comment by melMass** [comment]
Thanks @Patronogenesys , it's a [mistake](https://github.com/melMass/comfy_mtb/issues/40#issuecomment-1657175280) on my end I will fix it today

**Comment by melMass** [comment]
Fixed in https://github.com/melMass/comfy_mtb/commit/91f60d4c463c474ac10e868e8e73e13fa019856b
