### ISSUE TITLE
[bug] Failed to import module 'gpfgan' and 'frame_interpolation' (git submodules?)

### ISSUE THREAD

**Issue by GrafiTom** [melMass/comfy_mtb#59]
### Describe the bug

I am so close now.
Installed over ComfyUI portable version by running install script from python_embedded folder.
![hm001](https://github.com/melMass/comfy_mtb/assets/39159986/f1c1925e-8ded-45f0-9a1c-02958250fbbb)

finally the environment is detected correctly

![mhh002](https://github.com/melMass/comfy_mtb/assets/39159986/7f2e141a-2516-41e4-ad68-f1a329897b64)

everything installed.

### Expected behavior

should not see those two lines:
 
Failed to import module faceenhance because ModuleNotFoundError: No module named 'gfpgan'
 Failed to import module image_interpolation because ModuleNotFoundError: No module named 'frame_interpolation.eval'

### Platform and versions

```sh
Windows 10
ComfyUI portable
Python 3.10.3  "system"
```

### Console output

```sh
### ComfyUI Revision: 1262 [0cb14a33]
Log level: 20
[comfy_mtb] | WARNING -> Web extensions folder at D:\ComfyUI_portable\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
RestoreFace
LoadFaceEnhanceModel
LoadFilmModel
FilmInterpolation
ConcatImages
GetBatchFromHistory
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'gfpgan'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'frame_interpolation.eval'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/melMass/comfy_mtb/issues)
[comfy_mtb] | INFO -> Loaded the following nodes:
        Animation Builder (mtb): Convenient way to manage basic animation maths at the core of many of my workflows
        Smart Step (mtb): Utils to control the steps start/stop of the KAdvancedSampler in percentage
        Text To Image (mtb): Utils to convert text to image using a font
        Styles Loader (mtb): Load csv files and populate a dropdown from the rows (à la A111)
        Bbox From Mask (mtb): From a mask extract the bounding box
        Bbox (mtb): The bounding box (BBOX) custom type used by other nodes
        Crop (mtb): Crops an image and an optional mask to a given bounding box
        Uncrop (mtb): Uncrops an image to a given bounding box
        Debug (mtb): Experimental node to debug any Comfy values, support for more types and widgets is planned
        Save Tensors (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Deep Bump (mtb): Normal & height maps generation from single pictures
        Face Swap (mtb): Face swap using deepinsight/insightface models
        Load Face Swap Model (mtb): Loads a faceswap model
        Load Face Analysis Model (mtb): Loads a face analysis model
        Qr Code (mtb): Basic QR Code generator
        Unsplash Image (mtb): Unsplash Image given a keyword and a size
        String Replace (mtb): Basic string replacement
        Fit Number (mtb): Fit the input float using a source and target range
        Color Correct (mtb): Various color correction methods
        Image Compare (mtb): Compare two images and return a difference image
        Blur (mtb): Blur an image using a Gaussian filter.
        Mask To Image (mtb): Converts a mask (alpha) to an RGB image with a color and background
        Colored Image (mtb): Constant color image of given size
        Image Premultiply (mtb): Premultiply image with mask
        Image Resize Factor (mtb): Extracted mostly from WAS Node Suite, with a few edits (most notably multiple image support) and less features.
        Save Image Grid (mtb): Save all the images in the input batch as a grid of images.
        Load Image From Url (mtb): Load an image from the given URL
        Save Gif (mtb): Save the images from the batch as a GIF
        Export To Prores (mtb): Export to ProRes 4444 (Experimental)
        Latent Lerp (mtb): Linear interpolation (blend) between two latent vectors
        Image Remove Background Rembg (mtb): Removes the background from the input using Rembg.
        Float To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" FLOAT to a NUMBER.
        Int To Bool (mtb): Basic int to bool conversion
        Int To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" INT to a NUMBER.
        Transform Image (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Load Image Sequence (mtb): Load an image sequence from a folder. The current frame is used to determine which image to load.
        Save Image Sequence (mtb): Save an image sequence to a folder. The current frame is used to determine which image to save.
Total VRAM 12287 MB, total RAM 32715 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\ComfyUI_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 190 nodes successfully.
```

### Additional context

I am so close now. Just need guidance for those to modules.
Should I install some of the wheels releassed?

Thank you!

**Comment by melMass** [comment]
Oh this is a simple one :) 

You need to clone the [submodules](https://github.com/melMass/comfy_mtb/tree/main/extern) (Comfy Manager does it for you but I need to release the fixes I mentioned earlier)

So it should be for you:
```cmd
cd D:\ComfyUI_portable\ComfyUI\custom_nodes\comfy_mtb
git submodule update --init --recursive
```

And restart the server

**Comment by GrafiTom** [comment]
Thank you! :)  It worked.

FaceSwap working!

but now Tensorflow module popped up at the fail section. :)



![hmmm3](https://github.com/melMass/comfy_mtb/assets/39159986/45f5aaeb-b7bc-4800-a261-d1952daa09b8)

**Comment by melMass** [comment]
I should not bail completely of those just for tensorflow, I'll adjust it since installing the old tensorflow is what "breaks" comfy on windows embedded and that I'm trying to fix in the install.py. But it's only needed for the film nodes

**Comment by melMass** [comment]
Oh my bad I misread, yes so you are only missing the FILM nodes. If you want to test them (but it will be super slow) run (again from the right python.exe!!):
`python.exe -m pip install tensorflow`

If you feel adventurous and need speed on FILM (using  your GPU), but the risk of downgrading other dependencies in your env:
`python.exe -m pip install tensorflow==2.10.1`

**Comment by GrafiTom** [comment]
I can live without FILM nodes for now. :)
Animation workflow needs this node tho.

![hmmm4](https://github.com/melMass/comfy_mtb/assets/39159986/a1ea2f0d-169d-4511-917d-96984c96127a)

**Comment by GrafiTom** [comment]
> ```batchfile
> git submodule update --init --recursive
> ```

Yeah, installing Tensorflow with any of these commands 'break" comfyUI for me.
Uninstalling got it back to work. But now FaceSwap nodes not loading again. :)

I think I will wait for a more stable release. Had a lot of fun with faceswap tho.

**Comment by melMass** [comment]
>Animation workflow needs this node tho.

Thanks, that should not be the case, I'll fix that!
Regarding FILM, I will also look into similar models soon like RIFE etc

**Comment by GrafiTom** [comment]
Okay, I see you fixed getbatchfromhistory. 
Grabbed the graphutils.py  and it works now. :) thanks

Still dunno what happened to FaceSwap nodes.. getting this again.

![again](https://github.com/melMass/comfy_mtb/assets/39159986/ec75e64d-1e65-4a07-8622-a0ff8add041f)

Tried that submodule magic, but this time it did nothing. :)

cd D:\ComfyUI_portable\ComfyUI\custom_nodes\comfy_mtb
git submodule update --init --recursive

**Comment by melMass** [comment]
> Still dunno what happened to FaceSwap nodes.. getting this again.

When running Comfy, mtb should "explain", why those specific nodes fail, if you can find that it will help

> Maybe was a bit early to grab that .py

Aha yep, I was using a custom `BOOL` type but now comfy support litegraph's native toggles using `BOOLEAN`, that also allow to convert them to input <-> widgets

**Comment by GrafiTom** [comment]
> > Still dunno what happened to FaceSwap nodes.. getting this again.
> 
> When running Comfy, mtb should "explain", why those specific nodes fail, if you can find that it will help
> 
> > Maybe was a bit early to grab that .py
> 
> Aha yep, I was using a custom `BOOL` type but now comfy support litegraph's native toggles using `BOOLEAN`, that also allow to convert them to input <-> widgets

![fcsw](https://github.com/melMass/comfy_mtb/assets/39159986/f2084f6e-b400-4ba4-868d-6401de555599)

**Comment by AIMusicExperiment** [comment]
Sounds like you are making good progress on this. Is it time that we who are a bit less tech savvy should try to get this to work? Or should I continue to wait?

**Comment by melMass** [comment]
> Sounds like you are making good progress on this. Is it time that we who are a bit less tech savvy should try to get this to work? Or should I continue to wait?

Yep released now :) the only remaining problematic issue is still tensorflow on windows but it only affects the FILM nodes. I striped  down the install a lot it should work better overall

**Comment by GrafiTom** [comment]
Testing soon. I will catch some bugs for you. :)On 2023. Aug 13., at 0:26, Mel Massadian ***@***.***> wrote:﻿

Sounds like you are making good progress on this. Is it time that we who are a bit less tech savvy should try to get this to work? Or should I continue to wait?

Yep released now :) the only remaining problematic issue is still tensorflow on windows but it only affects the FILM nodes. I striped  down the install a lot it should work better overall
