### ISSUE TITLE
After generating animated GIF the preview overlay stays there forever [bug] 

### ISSUE THREAD

**Issue by GrafiTom** [melMass/comfy_mtb#63]
### Describe the bug

After generating animated GIF the preview overlay stays there forever, even if you load a new workflow.
ComfyUI needs to be restarted to clear.

![GIF](https://github.com/melMass/comfy_mtb/assets/39159986/b65dbeff-3a82-422b-80ea-783614b98f80)

### Reproduction

1. Run animation deforum example
2. See result
3. try to load another workflow

### Expected behavior

We need something to close that node. 

### Platform and versions

```sh
windows 10
python embeded
comfyui
```

**Comment by melMass** [comment]
Thanks for the report it is indeed very annoying

**Comment by GrafiTom** [comment]
it's working :) thank you
