### ISSUE TITLE
[bug] No module named 'termcolor'

### ISSUE THREAD

**Issue by GrafiTom** [melMass/comfy_mtb#64]
### Describe the bug

Latest version installed. Did it from ComfyUI manager. First uninstalled comfy_mtb nodes. Restart.
Then install comfy_mtb nodes from manager. Restart.

On start that's the error message.

![termcolor](https://github.com/melMass/comfy_mtb/assets/39159986/07c9b576-788a-4475-aa94-436afd85a536)

Example 01 - faceswap missing nodes

![01fswp](https://github.com/melMass/comfy_mtb/assets/39159986/6f7532ec-96d7-4fcd-9aee-3d9461e86c2f)

Example 02- missing nodes

![02film](https://github.com/melMass/comfy_mtb/assets/39159986/bd186b97-788d-499c-9587-97db6377b85a)

Example 03 - works

Example 04 - works

### Reproduction

Install from ComfyUI after uninstall.

### Expected behavior

All the nodes.

### Platform and versions

```sh
Windows 10
ComfyUI - Python Embeded
```

**Comment by melMass** [comment]
Can you provide the install log? ComfyManager should have created a comfyui.log file at the root of comfy_mtb you can attach it!

**Comment by GrafiTom** [comment]
Hmm strange. I have no log file in that folder. Searched *.log for the entire ComfyUI and found only one in the root directory which has only the latest run logged.

**Comment by melMass** [comment]
I did not test this functionality yet, I asked data about adding it to ComfyManager exactly for cases like this last week which I think they did (https://github.com/ltdrdata/ComfyUI-Manager/commit/41999f4e686368440150a3d46f23ecb40b17191b) I'm not in front of it to properly test today I will be able to tomorrow.

From the look of it it seems like it's the classic error with mtb: tensorflow's old version which is also breaking protobuf

**Comment by GrafiTom** [comment]
Maybe I should update Comfy manager too :)

**Comment by GrafiTom** [comment]
Okay, here is what I did.
All the missing modules that was listed on the startup as not found..  I copied them from my system python.
python310\Lib\site-packages  --->  python_embeded\Lib\site-packages

And now everything is working. 
Except FILM workflow.

**Comment by pennyvc** [comment]
same Issue here with same nodes, in fact I did a tutorial including an MTB node and have since had 4-5 reports from youtube, reddit and discord that mtb is failing on these nodes.

**Comment by melMass** [comment]
@pennyvc using the comfy manager?
I think there was an issue about system python being used instead of the env one but it has since been patched. I'll double check

**Comment by pennyvc** [comment]
could be comfymanager, would not surprise me though. the issues were all mostly related to colored image node not being found.

**Comment by melMass** [comment]
Is this still an issue?

@GrafiTom thanks a lot for the sponsor, it means a lot!

@pennyvc I just checked your youtube channel and it's some of the best video material I have seen on comfyui! I subscribed :)

**Comment by GrafiTom** [comment]
> I copied them from my system python.
> python310\Lib\site-packages ---> python_embeded\Lib\site-packages

You are welcome mate.

As I wrote before, for me the solution was this:  " I copied them from my system python.
python310\Lib\site-packages ---> python_embeded\Lib\site-packages"

**Comment by pennyvc** [comment]
hope you get any bugs sorted was having   enough trouble  i had to remove
mtb. which is  dissappointing as 90% of it worked fine 😭

**Comment by melMass** [comment]
closed by: https://github.com/melMass/comfy_mtb/commit/5dfea51dd8db2a4829e559eadeda22374b51c8a4
