### ISSUE TITLE
[feat] Ability or Doc to Disable Image Feed

### ISSUE THREAD

**Issue by ItsAstraLight** [melMass/comfy_mtb#68]
### Describe the problem

An easy way to remove or toggle the Image Feed feature aside from pulling the imagefeed.json (or it at least doc'd somewhere). Took me a bit to figure it out having not done much of any coding. I get a UI bug on my end (Ref 0), that makes it so I can't clear images. I usually do loops that make 40+ images and the Image Feed gets busy less I refresh the page

~ _Fantastic nodes btw, thank you very much_ ~

Ref 0: Image feed options are blocked by another UI element
![image](https://github.com/melMass/comfy_mtb/assets/114743776/dd819a0c-4c40-421e-81dd-174b4261bf8e)

### Describe the solution you'd like

A short addition to the docs on what file to pull, or a toggle of some kind.

**Comment by melMass** [comment]
I thought I fixed that!
Do you use something special for the toolbar to take full height like that? I think there is a vertical breakpoint on it, so if the window gets too small it does that but it should not otherwise and you can move it

**Comment by ItsAstraLight** [comment]
> I thought I fixed that! Do you use something special for the toolbar to take full height like that? I think there is a vertical breakpoint on it, so if the window gets too small it does that but it should not otherwise and you can move it

Uh oh, It's probably the "remember menu size" or something toggle and it just got anchored there because I'm always tossing the window between monitors and such. Thank you thank you
