### ISSUE TITLE
[bug] Film Interpolation only GIF no Image Sequence?

### ISSUE THREAD

**Issue by MushroomFleet** [melMass/comfy_mtb#69]
### Describe the bug

Forgive me if i have missed a node, however i cannot see a way to save the image sequence created by FILM interpolate. It works great to save a GIF, however i would really find the images more useful. 

Is there an example of how these images can be saved from the FILM node?

Thanks

### Reproduction

1. use FILM interp Json example
2. Try to save the image sequence (not a Gif)

Gif compression can be very Lossy.

### Expected behavior

Save image sequence to /output

### Platform and versions

```sh
Windoze
```

**Comment by melMass** [comment]
Yes you can use the default `ImageSave` node for image frames, there is also `ExportWithFfmpeg` for video but it is not really feature rich yet though

**Comment by MushroomFleet** [comment]
> 

thanks for the tips! 
in the end i used your "Export to ProRes" node and loaded the .mov into an editor, this is amazing and exactly what i needed. Thanks for your hard work on these nodes!! Thanks again :)
