### ISSUE TITLE
[feat] Export with Ffmpeg to custom path?

### ISSUE THREAD

**Issue by AIMusicExperiment** [melMass/comfy_mtb#70]
### Describe the bug

Really excited to use these new nodes.  I've been playing with the example workflow for the animation builder and I think it is awesome. But I want to use the Export with Ffmpeg to save to video. The settings are clear, but I don't see how to export. There is no place to put a path.  Am I supposed to use another node connected to the video out? Oh and by the way thanks for creating these nodes!  

### Platform and versions

```sh
windows
compyUi portable on stable swarm
```

**Comment by melMass** [comment]
Thanks!
Yes for now it's very primitive like save GIF, it saves it into the default output folder (if you did not change defaults or pass a CLI arg, it's `ComfyUI/outputs`) using a random uuid!

It should definitely offer more control

**Comment by melMass** [comment]
We all use VHS now
