### ISSUE TITLE
[bug] Not able to install Models, Install of mtb in ComfyUI still shows missing nodes

### ISSUE THREAD

**Issue by Tikishark777** [melMass/comfy_mtb#71]
### Describe the bug

I'm trying to use the mtb nodes.  I've installed through the manager, but ComfyUI still shows the following nodes missing.

When loading the graph, the following node types were not found:
Face Swap (mtb)
Load Face Enhance Model (mtb)
Load Face Analysis Model (mtb)
Load Face Swap Model (mtb)
Restore Face (mtb)
Nodes that have failed to load will show as red on the graph

I've tried uninstalling and reinstalling mtb, but received the same error each time.

I thought perhaps that it was because the models were missing so I tried the python download_models.py script in the script folder, but I received the following error message:

ModuleNotFoundError: No module named 'requests'

I also tried to install the dependencies, but received this error when running python get_deps.py

\ComfyUI\custom_nodes\comfy_mtb\scripts\get_deps.py", line 5, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

### Platform and versions

```sh
Windows
```

### Console output

```sh
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'gfpgan'
        Failed to import module faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'frame_interpolation.eval'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/melMass/comfy_mtb/issues)
```

**Comment by s-marcelle** [comment]
I've been having the same issue. I hope that some solution is eventually attained.

**Comment by melMass** [comment]
@s-marcelle Also using the manager?
Because all of the logs from the OPs report suggest that not, gfpgan and frame_interpolation are shipped with mtb (in the extern folder), you must clone the repository with submodules (comfy manager does it all for you)

**Comment by s-marcelle** [comment]
> 

Yes I installed via the manager as instructed....

And I am also experiencing the same as the person who raised the issue.

**Comment by melMass** [comment]
> And I am also experiencing the same as the person who raised the issue.

The OP has multiple issues: 

- none of the script they run manually should be (get_deps, model_downloads), they are there useful for people who can simply read them, but not mentioned in the base instructions for this reason. (I'm pretty sure request comes with comfy portable btw). The models can be downloaded from the comfy manager directly.
- The project gets downloaded without the submodules (`gfpgan` and `frame_interpolation`), this is apparently a thing on very old git, I just learned that from DataIt after this issue was posted on the element board.

That's why I usually suggest openining dedicated issues with your own log unless it's not a generic issue but "not able to install" is too broad and it's unclear what you mean by "same" here

**Comment by s-marcelle** [comment]
Ok I will share my issues

**Comment by Tikishark777** [comment]
I'm not sure if a solution has been found?  You never responded to my request.  Would you clarify what you want me to do to install this extension?  I initially used control manager and installed Mtb.  I looked at the download_models script, but I'm not sure if you're asking me to manually download each one?  You say that the control manager automatically downloads all the models, but that's not happening for me.  Help would be appreciated.

**Comment by melMass** [comment]
You are having multiple unrelated things happening, I did address your points in my answers...

Here you can click Install models and look for the ones you need, I plan to add a new UI in `/mtb`'s endpoint for those who can't either run my model download script or Comfy Manager's download ui. 
![image](https://github.com/melMass/comfy_mtb/assets/7041726/ad0863c4-d365-4664-a6e6-8d2e59ee1665)

Just check my previous answers but something went wrong during your install and it did not pull the submodules (gfpgan, frame_interpolation)

For insightface you can try to manually running this, but the install script handle much more:


`pip install https://github.com/melMass/comfy_mtb/releases/download/v0.1.3/insightface-0.7.3-cp310-cp310-win_amd64.whl`

**Comment by justanotherbug** [comment]
Just did a fresh install of comfy and installed the node from manager and still does not install properly.
here is the cmd text.


g:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-08-25 12:32:42.819610

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension


## ComfyUI-Manager: EXECUTE => ['g:\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py']

## Execute install/(de)activation script for 'g:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb'
[!] Traceback (most recent call last):
[!]   File "g:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\install.py", line 26, in <module>
[!]     elif "python_embeded" in executable:
[!] TypeError: argument of type 'WindowsPath' is not iterable
install/(de)activation script failed: g:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.2 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 32669 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using xformers cross attention
Web extensions folder found at G:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
### Loading: ComfyUI-Impact-Pack (V3.24.5)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2)
### Loading: ComfyUI-Manager (V0.26.2)
### ComfyUI Revision: 1338 [e3d0a9a4]
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Traceback (most recent call last):
  File "g:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 24, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 3, in <module>
    from scripts.faceswap import FaceSwapScript, get_models
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\faceswap.py", line 13, in <module>
    from scripts.swapper import UpscaleOptions, swap_face
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\swapper.py", line 10, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[comfy_mtb] | WARNING -> Web extensions folder at G:\ComfyUI_windows_portable\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | STATUS -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import module faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import module generate because ModuleNotFoundError: No module named 'qrcode'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/melMass/comfy_mtb/issues)
[comfy_mtb] | STATUS -> Loaded the following nodes:
        Animation Builder (mtb): Convenient way to manage basic animation maths at the core of many of my workflows
        Smart Step (mtb): Utils to control the steps start/stop of the KAdvancedSampler in percentage
        Styles Loader (mtb): Load csv files and populate a dropdown from the rows (à la A111)
        Interpolate Clip Sequential (mtb): -
        Bbox From Mask (mtb): From a mask extract the bounding box
        Bbox (mtb): The bounding box (BBOX) custom type used by other nodes
        Crop (mtb): Crops an image and an optional mask to a given bounding box
        Uncrop (mtb): Uncrops an image to a given bounding box
        Debug (mtb): Experimental node to debug any Comfy values, support for more types and widgets is planned
        Save Tensors (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Deep Bump (mtb): Normal & height maps generation from single pictures
        String Replace (mtb): Basic string replacement
        Fit Number (mtb): Fit the input float using a source and target range
        Get Batch From History (mtb): Very experimental node to load images from the history of the server.
        Any To String (mtb): Tries to take any input and convert it to a string
        Color Correct (mtb): Various color correction methods
        Image Compare (mtb): Compare two images and return a difference image
        Blur (mtb): Blur an image using a Gaussian filter.
        Mask To Image (mtb): Converts a mask (alpha) to an RGB image with a color and background
        Colored Image (mtb): Constant color image of given size
        Image Premultiply (mtb): Premultiply image with mask
        Image Resize Factor (mtb): Extracted mostly from WAS Node Suite, with a few edits (most notably multiple image support) and less features.
        Save Image Grid (mtb): Save all the images in the input batch as a grid of images.
        Load Image From Url (mtb): Load an image from the given URL
        Save Gif (mtb): Save the images from the batch as a GIF
        Export With Ffmpeg (mtb): Export with FFmpeg (Experimental)
        Latent Lerp (mtb): Linear interpolation (blend) between two latent vectors
        Image Remove Background Rembg (mtb): Removes the background from the input using Rembg.
        Float To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" FLOAT to a NUMBER.
        Int To Bool (mtb): Basic int to bool conversion
        Int To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" INT to a NUMBER.
        Transform Image (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Load Image Sequence (mtb): Load an image sequence from a folder. The current frame is used to determine which image to load.
        Save Image Sequence (mtb): Save an image sequence to a folder. The current frame is used to determine which image to save.
Traceback (most recent call last):
  File "g:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 183, in <module>
    from .endpoint import endlog
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 9, in <module>
    import requirements
ModuleNotFoundError: No module named 'requirements'

Cannot import G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: No module named 'requirements'
Total VRAM 12288 MB, total RAM 32669 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 192 nodes successfully.

        "The future depends on what you do today." - Mahatma Gandhi


Import times for custom nodes:
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.3 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds (IMPORT FAILED): G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.9 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   6.6 seconds: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready

**Comment by melMass** [comment]
I introduced this issue when trying to handle space in path (#73)
I just fixed it

**Comment by melMass** [comment]
Did it work :) ?

**Comment by Tikishark777** [comment]
No, unfortunately I've given up hope for now. I've tried clean installs, manually installing each component or/and using the custom manager. I'm going to try again in a few weeks in hopes that an updated version may help. Ty for trying to fix it.

**Comment by melMass** [comment]
Understandable! I will gather the recent feedbacks to try and fix some of these, I linked other projects for the faceswap and facerestore nodes in the README since most recent errors seems related to that, i think my install script is doing something that trip Comfy Manager

**Comment by cn112cn** [comment]
Anyone got a solution for this? I tried almost a dozen clean install, always the same error.

**Comment by melMass** [comment]
@cn112cn Please open a dedicated issue, both points from the OP's issue have been addressed in https://github.com/melMass/comfy_mtb/issues/71#issuecomment-1689690343 and https://github.com/melMass/comfy_mtb/issues/71#issuecomment-1692945975. The unrelated issue reported by  that has also been fixed since.
Since I still can't mind-read don't hesitate to join some log and informations about you system / Comfy install it saves time for spotting issues

**Comment by jetzwow** [comment]
So i was able to fix this issue on my install by uninstalling the modules that are not found and reinstalling them with the install script.

My error was:
`Failed to import module image_interpolation because ModuleNotFoundError: No module named 'insightface'`

So i went to custom_nodes\comfy_mtb, open PowerShell

Uninstall insightface
enter `path\to\python_embeded\python.exe -m pip uninstall insightface`

Reinstall using install.py
enter `path\to\python_embeded\python.exe install.py`

I did this for every ModuleNotFoundError Comfy threw out and was able to fix and load all mtb modules.

I do have a local Python as well as the embedded. The removed modules were installed under my local and now reinstalled under the embedded. So could it be some kind of PATH issue?

**Comment by LubuLubu2** [comment]
Mine was working up until 6 7 hours ago. Manager updated itself and MiT and boom, there is no faceswap anymore and all the nods shows missing.

**Comment by melMass** [comment]
Hi,

The problematic nodes are removed in the next version as comfy portable is now on python 11, more precisely they are optional, you can learn more about it in the readme where I link to alternatives: https://github.com/melMass/comfy_mtb#optional-nodes
