### ISSUE TITLE
Please change your paths in your JS files to relative. [bug] 

### ISSUE THREAD

**Issue by AIMusicExperiment** [melMass/comfy_mtb#74]
### Describe the bug

When using the Stable Swarm CompyUi backend some of you scripts won't run.  This is most notable in your animation builder as much of the node isn't there.  This is a well known problem with the Stable Swarm backend, an fortunately it is easy to fix by adding to your import paths. I know that this works as I keep fixing your files but they get broken every time I update your folder.  A great resource to solve this is the lead developer Alex mcmonky, at Stable Swarm. He has done pull requests for the bigger developers and they have all fixed their scripts. I hope that you can get this resolved so that your nodes will work properly for the many many folks that are or soon will be using stable swarm. THANKS!  

![Builder correct](https://github.com/melMass/comfy_mtb/assets/133187055/b8b9231d-9097-44ce-bf41-3f8d344c2551)
![Builder wrong](https://github.com/melMass/comfy_mtb/assets/133187055/28be91d3-7e10-4949-a253-192bb7cb5f0a)

### Platform and versions

```sh
Windows
compy portable
StableSwarm
```

**Comment by melMass** [comment]
Hi sorry I have no idea what you are referring too by relative paths in JS, can you explain more concretely?

**Comment by melMass** [comment]
I got an answer on the Element board since and pushed the fix based on this [PR edits](https://github.com/ltdrdata/ComfyUI-Manager/pull/43/files)!

Thanks for the report

**Comment by AIMusicExperiment** [comment]
Thanks! for taking care of this! As always "You Rock!"
