### ISSUE TITLE
[bug] incompatible with cuda 12.1

### ISSUE THREAD

**Issue by KevinParnell** [melMass/comfy_mtb#76]
### Describe the bug

I am using a venv so I already installed the reqs_windows file before running the regular default script with manager and run into this error:

`## ComfyUI-Manager: EXECUTE => ['F:\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py']

## Execute install/(de)activation script for 'F:\ComfyUI\custom_nodes\comfy_mtb'
[!] 2023-08-26 04:00:20.233713: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
[!] 2023-08-26 04:00:20.233781: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 [!][mtb install]  No arguments provided, doing a full install/update...
  Traceback (most recent call last):
[mtb install]  mtb install
 [!][mtb install]  Detected environment: unknown
   File "F:\ComfyUI\custom_nodes\comfy_mtb\install.py", line 540, in <module>
 [!][mtb install]  Checking environment...
      installed, pip_name, pip_spec, import_name = try_import(requirement)
                ? Package onnxruntime-gpu already installed (import name: 'onnxruntime').
[!]                     ? Package qrcode already installed (import name: 'qrcode').
  File "F:\ComfyUI\custom_nodes\comfy_mtb\install.py", line 361, in try_import
[!]                     ? Package rembg already installed (import name: 'rembg').
    import_module(import_name)
 [!]                    ? Package tensorflow already installed (import name: 'tensorflow').
    File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
                ? Package facexlib already installed (import name: 'facexlib').
[!]                     ? Package insightface already installed (import name: 'insightface').
    return _bootstrap._gcd_import(name[level:], package, level)
[!]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[!]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[!]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[!]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[!]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[!]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\__init__.py", line 3, in <module>
[!]     from .archs import *
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\archs\__init__.py", line 5, in <module>
[!]     from basicsr.utils import get_root_logger, scandir
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\utils\__init__.py", line 4, in <module>
[!]     from .misc import check_resume, get_time_str, make_exp_dirs, mkdir_and_rename, scandir, set_random_seed, sizeof_fmt
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\utils\misc.py", line 12, in <module>
[!]     IS_HIGH_VERSION = [int(m) for m in list(re.findall(r"^([0-9]+)\.([0-9]+)\.([0-9]+)([^0-9][a-zA-Z0-9]*)?(\+git.*)?$",\
[!] IndexError: list index out of range
install/(de)activation script failed: F:\ComfyUI\custom_nodes\comfy_mtb

[ComfyUI-Manager] Startup script completed.
#######################################################################

Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI\custom_nodes\rgthree-comfy
   7.5 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 24489 MB
2023-08-26 04:00:28.673183: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-08-26 04:00:28.673350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
Using pytorch cross attention
Web extensions folder found at F:\ComfyUI\web\extensions\ComfyLiterals
### ComfyUI Revision: 1344 [f72780a7]
F:\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Comfyroll Custom Nodes: Loaded
F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mediapipe_face\mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
[comfy_mtb] | WARNING -> Web extensions folder at F:\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because IndexError: list index out of range`

I am using cuda 12.1 and the nightly version of torch to use some newer features and it seems like not using cuda 11.1 is the root cause of this issue.

### Reproduction

1. install cuda 12.1 and nightly torch
2. install node in comfy with manager and run reqs script
3. let manager install node when relaunching comfyui

### Expected behavior

I expected it to load the faceenhance node

### Platform and versions

```sh
- windows 11
- recommended version of python
- cuda 12.1
= nightly torch
- up to date version of comfy
```

### Console output

```sh
`## ComfyUI-Manager: EXECUTE => ['F:\\ComfyUI\\venv\\Scripts\\python.exe', 'install.py']

## Execute install/(de)activation script for 'F:\ComfyUI\custom_nodes\comfy_mtb'
[!] 2023-08-26 04:00:20.233713: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
[!] 2023-08-26 04:00:20.233781: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
 [!][mtb install]  No arguments provided, doing a full install/update...
  Traceback (most recent call last):
[mtb install]  mtb install
 [!][mtb install]  Detected environment: unknown
   File "F:\ComfyUI\custom_nodes\comfy_mtb\install.py", line 540, in <module>
 [!][mtb install]  Checking environment...
      installed, pip_name, pip_spec, import_name = try_import(requirement)
                ? Package onnxruntime-gpu already installed (import name: 'onnxruntime').
[!]                     ? Package qrcode already installed (import name: 'qrcode').
  File "F:\ComfyUI\custom_nodes\comfy_mtb\install.py", line 361, in try_import
[!]                     ? Package rembg already installed (import name: 'rembg').
    import_module(import_name)
 [!]                    ? Package tensorflow already installed (import name: 'tensorflow').
    File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
                ? Package facexlib already installed (import name: 'facexlib').
[!]                     ? Package insightface already installed (import name: 'insightface').
    return _bootstrap._gcd_import(name[level:], package, level)
[!]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[!]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[!]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[!]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[!]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[!]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\__init__.py", line 3, in <module>
[!]     from .archs import *
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\archs\__init__.py", line 5, in <module>
[!]     from basicsr.utils import get_root_logger, scandir
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\utils\__init__.py", line 4, in <module>
[!]     from .misc import check_resume, get_time_str, make_exp_dirs, mkdir_and_rename, scandir, set_random_seed, sizeof_fmt
[!]   File "F:\ComfyUI\venv\lib\site-packages\basicsr\utils\misc.py", line 12, in <module>
[!]     IS_HIGH_VERSION = [int(m) for m in list(re.findall(r"^([0-9]+)\.([0-9]+)\.([0-9]+)([^0-9][a-zA-Z0-9]*)?(\+git.*)?$",\
[!] IndexError: list index out of range
install/(de)activation script failed: F:\ComfyUI\custom_nodes\comfy_mtb

[ComfyUI-Manager] Startup script completed.
#######################################################################


Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI\custom_nodes\rgthree-comfy
   7.5 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 24489 MB
2023-08-26 04:00:28.673183: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2023-08-26 04:00:28.673350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 : cudaMallocAsync
Using pytorch cross attention
Web extensions folder found at F:\ComfyUI\web\extensions\ComfyLiterals
### Loading: ComfyUI-Impact-Pack (V3.24.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2)
### Loading: ComfyUI-Manager (V0.26.2)
### ComfyUI Revision: 1344 [f72780a7]
F:\ComfyUI\venv\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
Comfyroll Custom Nodes: Loaded
F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\mediapipe_face\mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
[comfy_mtb] | WARNING -> Web extensions folder at F:\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because IndexError: list index out of range`
```

**Comment by melMass** [comment]
Thanks for the report, why do you think it's related to CUDA 12?

I realized yesterday that nightly uses python 11, but there are some issues currently.

long story short, for reasons I still don't get Tensorflow dropped GPU support on windows native (you must use WSL so linux) https://github.com/tensorflow/tensorflow/issues/59918#issuecomment-1677217270

The version I pin in mtb is the latest that does have GPU but it's old, and doesn't support >3.10 but that's only for the FILM nodes iirc.

**Comment by melMass** [comment]
closed by: https://github.com/melMass/comfy_mtb/commit/5dfea51dd8db2a4829e559eadeda22374b51c8a4
