### ISSUE TITLE
[bug] can't detect or install some modules

### ISSUE THREAD

**Issue by shrewen** [melMass/comfy_mtb#77]
### Describe the bug

Trying to install the reqs but I'm getting this message

`ERROR: pycocotools-2.0.6-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.`

plus these nodes are failing to load even though they're installed

`[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import module faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import module image_interpolation because ModuleNotFoundError: No module named 'tensorflow'
        Failed to import module mask because ModuleNotFoundError: No module named 'rembg'`

I've checked the other issues similar to this one but none of the solutions work for me.

### Reproduction

Installed the extension via ComfyManager

### Platform and versions

```sh
OS: Windows
ComfyUI: standalone, also Portable was giving me the same errors
```

**Comment by melMass** [comment]
Hey sorry it seems I haven't seen your issue before now, did you abandon or solved it 😁?

**Comment by shrewen** [comment]
Hi Mel,No worries, I think it was an issue with the nightly torch build, I got the comfyui portable with stable torch and it worked, but since I'm not entirely sure what was wrong I left the comment a blank.
-------- Original message --------From: Mel Massadian ***@***.***> Date: 8/28/23  4:30 PM  (GMT+02:00) To: melMass/comfy_mtb ***@***.***> Cc: shrewen ***@***.***>, State change ***@***.***> Subject: Re: [melMass/comfy_mtb] [bug] can't detect or install some modules (Issue #77) 
Hey sorry it seems I haven't seen your issue before now, did you abandon or solved it 😁?
