### ISSUE TITLE
[feat] Add string with/without start at frame

### ISSUE THREAD

**Issue by Cedri4** [melMass/comfy_mtb#78]
### Describe the problem

Add string: node where you  add string if possible with start at frame and end at frame
Remove string: node where you  remove string if possible with start at frame and end at frame
They work like replace string

### Describe the solution you'd like

![Nouveau projet (2)](https://github.com/melMass/comfy_mtb/assets/93396286/9486d3a2-5d35-413a-9a25-8931f8149f40)
with start at frame and end at frame

**Comment by melMass** [comment]
I will look into this tomorrow but I think as a separate node, do you have a specific use case that could help thinking about it?

**Comment by melMass** [comment]
Sorry I never looked into this! I think you can find much better approaches in the Fizz Nodes, I did not test them yet but they are used for prompt travel in animateDiff Evolved samples: https://github.com/FizzleDorf/ComfyUI_FizzNodes

I'll keep the issue open for now
