### ISSUE TITLE
No module named 'requirements', Import Failed at startup [bug] 

### ISSUE THREAD

**Issue by MushroomFleet** [melMass/comfy_mtb#82]
### Describe the bug

When you startup comfy:

```
Traceback (most recent call last):
  File "D:\MACHINES\comfy-July\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\MACHINES\comfy-July\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 183, in <module>
    from .endpoint import endlog
  File "D:\MACHINES\comfy-July\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 9, in <module>
    import requirements
ModuleNotFoundError: No module named 'requirements'

Cannot import D:\MACHINES\comfy-July\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: No module named 'requirements'
```

### Reproduction

1. Updated the MTB custom nodes
2. Started ComfyUI
3. received the above error 

Import failed, nodes are not available.

### Expected behavior

I was using the nodes with a previous version just fine until i updated.

ModuleNotFoundError: No module named 'requirements'

### Platform and versions

```sh
Windows, Standalone
```

### Console output

```sh
Traceback (most recent call last):
  File "D:\MACHINES\comfy-July\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\MACHINES\comfy-July\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 183, in <module>
    from .endpoint import endlog
  File "D:\MACHINES\comfy-July\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 9, in <module>
    import requirements
ModuleNotFoundError: No module named 'requirements'

Cannot import D:\MACHINES\comfy-July\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: No module named 'requirements'
Total VRAM 24563 MB, total RAM 65451 MB
xformers version: 0.0.14.dev
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
```

**Comment by MoAlSeifi** [comment]
I think I just fixed this problem with install [requirements.py](https://pypi.org/project/requirements.py/) module:
`.\python_embeded\python.exe -m pip install requirements.py`

I ran into another bug after fixing the requirements error, which is:

> Failed to import module mask because ModuleNotFoundError: No module named 'platformdirs'
and I fixed it with installing the platformdirs module the same way I installed requrements.py, but it installed in my main python site-packages so i manually copied the package in the comfyui python site-package folder.

but I'm still getting the missing nodes error in the comfyUI.

**Comment by p0mad** [comment]
@MushroomFleet 
I mostly have the same problems. i think it is related to the ENV!
I asked to provide and export of his env to be able to follow the work in #79

**Comment by MushroomFleet** [comment]
> @MushroomFleet I mostly have the same problems. i think it is related to the ENV! I asked to provide and export of his env to be able to follow the work in #79

Thanks but i read your thread and our issue looks different here.


**step 1.** update comfy.
**step 2.** Error: Requirements module not found, Comfy cannot load the nodes at startup.

**Comment by melMass** [comment]
I think it's due to my misunderstanding of comfy manager, I thought it ran the install.py each time you update the nodes but apparently not since `requirement-parser` is installed at this stage.

I will just add some safer fallback for these today or tomorrow
