### ISSUE TITLE
[bug] how to fix:No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

### ISSUE THREAD

**Issue by silence11702** [melMass/comfy_mtb#83]
### Describe the bug

[comfy_mtb] | WARNING -> Web extensions folder at D:\AI\ComfyUI\web\extensions\mtb is not a symlink, if updating please delete it before
C:\Program Files\Python310\lib\site-packages\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
[comfy_mtb] | INFO -> Some nodes failed to load:
        Failed to import module faceswap because ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.defs'; 'onnx.onnx_cpp2py_export' is not a package

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/melMass/comfy_mtb/issues)
[comfy_mtb] | INFO -> Loaded the following nodes:
        Animation Builder (mtb): Convenient way to manage basic animation maths at the core of many of my workflows
        Smart Step (mtb): Utils to control the steps start/stop of the KAdvancedSampler in percentage
        Styles Loader (mtb): Load csv files and populate a dropdown from the rows (à la A111)
        Interpolate Clip Sequential (mtb): -
        Bbox From Mask (mtb): From a mask extract the bounding box
        Bbox (mtb): The bounding box (BBOX) custom type used by other nodes
        Crop (mtb): Crops an image and an optional mask to a given bounding box
        Uncrop (mtb): Uncrops an image to a given bounding box
        Debug (mtb): Experimental node to debug any Comfy values, support for more types and widgets is planned
        Save Tensors (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Deep Bump (mtb): Normal & height maps generation from single pictures
        Restore Face (mtb): Uses GFPGan to restore faces
        Load Face Enhance Model (mtb): Loads a GFPGan or RestoreFormer model for face enhancement.
        Qr Code (mtb): Basic QR Code generator
        Unsplash Image (mtb): Unsplash Image given a keyword and a size
        Text To Image (mtb): Utils to convert text to image using a font
        String Replace (mtb): Basic string replacement
        Fit Number (mtb): Fit the input float using a source and target range
        Get Batch From History (mtb): Very experimental node to load images from the history of the server.
        Any To String (mtb): Tries to take any input and convert it to a string
        Load Film Model (mtb): Loads a FILM model
        Film Interpolation (mtb): Google Research FILM frame interpolation for large motion
        Concat Images (mtb): Add images to batch
        Color Correct (mtb): Various color correction methods
        Image Compare (mtb): Compare two images and return a difference image
        Blur (mtb): Blur an image using a Gaussian filter.
        Mask To Image (mtb): Converts a mask (alpha) to an RGB image with a color and background
        Colored Image (mtb): Constant color image of given size
        Image Premultiply (mtb): Premultiply image with mask
        Image Resize Factor (mtb): Extracted mostly from WAS Node Suite, with a few edits (most notably multiple image support) and less features.
        Save Image Grid (mtb): Save all the images in the input batch as a grid of images.
        Load Image From Url (mtb): Load an image from the given URL
        Save Gif (mtb): Save the images from the batch as a GIF
        Export With Ffmpeg (mtb): Export with FFmpeg (Experimental)
        Latent Lerp (mtb): Linear interpolation (blend) between two latent vectors
        Image Remove Background Rembg (mtb): Removes the background from the input using Rembg.
        Float To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" FLOAT to a NUMBER.
        Int To Bool (mtb): Basic int to bool conversion
        Int To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" INT to a NUMBER.
        Transform Image (mtb): Save torch tensors (image, mask or latent) to disk, useful to debug things outside comfy
        Load Image Sequence (mtb): Load an image sequence from a folder. The current frame is used to determine which image to load.
        Save Image Sequence (mtb): Save an image sequence to a folder. The current frame is used to determine which image to save.

### Platform and versions

```sh
win
```

**Comment by silence11702** [comment]
i had try pip install onnx==1.12.0,and retry, but still not working

**Comment by melMass** [comment]
Hi, I need more info like the comfy mode (portable or using a custom env), the python version etc..

**Comment by melMass** [comment]
Hi,

These nodes are now optional and not "first" class in mtb, you can read more about it here: https://github.com/melMass/comfy_mtb#optional-nodes

I suggest using this for now, they might come back if I manage to solve the dependency mess it introduces:
https://github.com/Gourieff/comfyui-reactor-node
