### ISSUE TITLE
[bug] Debug node "*" inputs cause prompt validation errors.

### ISSUE THREAD

**Issue by ali1234** [melMass/comfy_mtb#85]
### Describe the bug

The debug node is supposed to be able to handle any input type. Its input type is "*" but this no longer seems to work. Connecting for example a latent to the anything_1 input causes the following error:

```
Failed to validate prompt for output 9:
* (prompt):
  - Return type mismatch between linked nodes: anything_1, LATENT != *
* Debug (mtb) 9:
  - Return type mismatch between linked nodes: anything_1, LATENT != *
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': 'Return type mismatch between linked nodes: anything_1, LATENT != *', 'extra_info': {}}
```

### Reproduction

1. Add an "Empty Latent Image" node
2. Add a debug node 
3. Connect latent output to anything_1 input
4. Queue prompt

### Expected behavior

The debug node should log the shape of the input latent tensor to the console.

### Platform and versions

```sh
Linux, venv.
```

### Console output

```sh
got prompt
Failed to validate prompt for output 2:
* (prompt):
  - Return type mismatch between linked nodes: anything_1, LATENT != *
* Debug (mtb) 2:
  - Return type mismatch between linked nodes: anything_1, LATENT != *
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': 'Return type mismatch between linked nodes: anything_1, LATENT != *', 'extra_info': {}}
```

### Additional context

This is likely due to a change in Comfy.

This also affects the "Any to String" node.

**Comment by ali1234** [comment]
Upstream issue https://github.com/comfyanonymous/ComfyUI/issues/257

**Comment by melMass** [comment]
Hi, 

Thanks for the report, the issue you linked is quite old so I don't think it's related.
I just tried it and on latent it gives a weird output because it's a dict, but I can easily add a proper handler for it:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/3f5ef05a-2c98-4e09-bfcc-6a309e72279b)


Are you sure the web extension is properly installed? 

The install script does it but you must copy or symlink (shortcut):
`ComfyUI/custom_nodes/comfy_mtb/web` to `ComfyUI/web/extensions/mtb`

**Comment by ali1234** [comment]
I installed using comfy manager. It makes the symlink.

**Comment by ali1234** [comment]
This is what happens with latest comfy:

![image](https://github.com/melMass/comfy_mtb/assets/651970/5443e2d5-b8e4-4449-b1f3-065f605e13b2)

This is what is expected to happen according to the upstream bug, because the prompt validator compares the strings "*" and "LATENT" directly.

**Comment by melMass** [comment]
That's strange... let me update Comfy main to be sure on my end (I did two days ago maybe something came up since)

**Comment by melMass** [comment]
Yep I tried with the latest I don't have that issue.
I just pushed a few edits to not display the actual huge content of tensors but I can't reproduce your issue:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/4f4dab75-e8a8-414f-b08b-e8d3341bb47a)

**Comment by ali1234** [comment]
My comfy version is:

```
commit 36ea8784a875bde21c88f84dfb99475b6e8187e8 (HEAD -> master, origin/master, origin/HEAD)
Date:   Sat Sep 2 03:34:57 2023 -0400
```

Manager version:

```
commit 8b32f0f453709c8681ffb211a2f2d170ac18a0b9 (HEAD -> main, origin/main, origin/HEAD)
Date:   Sun Sep 3 02:24:11 2023 +0900
```

mtb version:

```
commit 638498c6b47c2b2cab82f76aec1f3d46df67f263 (HEAD -> main, origin/main, origin/HEAD)
Date:   Sat Sep 2 23:05:32 2023 +0200
```

Installed on Linux in a venv. This is a fresh clone of comfy. Nothing else is installed. I made it just now. The problem is reproducible.

The failing validation test is here: https://github.com/comfyanonymous/ComfyUI/blame/62efc78a4b13b87ef0df51323fe1bd71b433fa11/execution.py#L435

If I change this line of code to `if 0:` then the code runs and I see the expected debug output:

![image](https://github.com/melMass/comfy_mtb/assets/651970/17d43a2c-80b3-4ca1-800c-8e1163a49b75)

**Comment by jbluew** [comment]
Same error here.  Windows venv.

comfy:
commit cfe1c54de88e7525ec7e4189a8a3294dfc3cd4c0 (HEAD -> master, origin/master, origin/HEAD)
Date:   Thu Aug 31 15:16:58 2023 -0400

Manager:
commit 5e312206ec4300ad789fcd564f7269eb96df5862 (HEAD -> main, origin/main, origin/HEAD)
Merge: 434b16b a8aa9bf
Date:   Tue Aug 29 00:51:26 2023 +0900

mtb: commit e11df9d45c81d93f4334841de036b4aa3364375a (HEAD -> main, origin/main, origin/HEAD)
Date:   Sat Aug 26 17:27:33 2023 +0200

**Comment by melMass** [comment]
Are you 100% sure that you have the web folder symlinked? It looks to me like it's not up to date or there is a bug there (if you can check the web console or if there are relevant info in the python one do post them).

I just tried on windows, windows wsl, colab and a mac m1 and I cannot reproduce locally

**Comment by ali1234** [comment]
Yes, manager runs the install script and does this:

```
al@al-desktop:~/ComfyTest/web/extensions$ ls -l
total 8
drwxrwxr-x 2 al al 4096 Sep  2 22:51 core
-rw-rw-r-- 1 al al 1988 Aug 23 16:25 logging.js.example
lrwxrwxrwx 1 al al   45 Sep  2 22:57 mtb -> /home/al/ComfyTest/custom_nodes/comfy_mtb/web
```

**Comment by ali1234** [comment]
I also tried removing manager so that mtb is the only thing installed, and it still happens.

Anyway if I am right, the upstream bug is the cause, so you won't be able to fix it anyway.

There is also an unmerged pull request with a fix: https://github.com/comfyanonymous/ComfyUI/pull/770
