### ISSUE TITLE
[bug] Unable to unload MTB Nodes from Workspace

### ISSUE THREAD

**Issue by Phando** [melMass/comfy_mtb#89]
### Describe the bug

A dialog pops up making the ComfyUI unusable. 
![Screenshot 2023-09-07 at 12 07 42 PM](https://github.com/melMass/comfy_mtb/assets/215984/11139405-7729-474a-b95c-bd57770bbe72)

### Reproduction

1. Fresh install of ComfyUI Portable or ComfyUi Embedded on windows 
2. Install the Comfy Manager
3. Add the MTB Nodes, restart, add requirements, restart....
4. Open the #4 example
5. Try to load any other workflow
6. Error shows up  

### Expected behavior

Removing MTB nodes from the workspace should work just like any other nodes. 

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

**Comment by melMass** [comment]
Thanks for the report, it was a typo 🙈
