### ISSUE TITLE
[feat] Enhanced 'here' folder path

### ISSUE THREAD

**Issue by Phando** [melMass/comfy_mtb#90]
### Describe the problem

When there are symlinks in the path the here folder doesn't always resolve correctly. I was keeping my custom_nodes on my d: drive vs the comfy install on the c: drive. Custom_nodes was a symlink in my ComfiUI folder. When 'here' was being resolved it wound up following the path back on d: and not through the symlink to c: 

### Describe the solution you'd like

In utils.py change 'here' to be more consistent with other custom_nodes
 
```
# here = Path(__file__).parent.resolve()
here = Path(os.path.dirname(os.path.abspath(__file__)))

```

**Comment by melMass** [comment]
Thanks! I did not think of this case but it makes sense!
