### ISSUE TITLE
[bug] gfpgan get installed multiple times

### ISSUE THREAD

**Issue by wangdong2023** [melMass/comfy_mtb#92]
### Describe the bug

`gfpgan` get installed multiple times, one is under `ComfyUI\models\insightface`, the other under `ComfyUI\gfpgan`.

### Reproduction

1. do `python install.py`
2. populate `ComfyUI\models\insightface`
3. restart comfy

### Operating System

Linux

### Comfy Mode

In a custom virtual env (venv, virtualenv, conda...)

### Additional context

I think the `TencentARC/GFPGAN` library downloaded weight the second time. Then maybe the first one is not needed?

**Comment by melMass** [comment]
Hi, 

Thanks, can you show the content of both folders?

**Comment by wangdong2023** [comment]
Sure,
`ls models/insightface/*
models/insightface/detection_Resnet50_Final.pth       models/insightface/inswapper_128.onnx
models/insightface/detection_mobilenet0.25_Final.pth

models/insightface/models:
buffalo_l`

`ls gfpgan/*/*
gfpgan/weights/detection_Resnet50_Final.pth  gfpgan/weights/parsing_parsenet.pth
root@992198a8e978:/ComfyUI# ls models/insightface/*`

**Comment by melMass** [comment]
Hi sorry I did not see the response before.
It looks fine to me, you do need all these.
That said, those nodes are now removed from mtb because their maintenance was too heavy: https://github.com/melMass/comfy_mtb#optional-nodes
