### ISSUE TITLE
[feat] Add loopchain pipeline input to the animation builder

### ISSUE THREAD

**Issue by AIMusicExperiment** [melMass/comfy_mtb#93]
### Describe the problem

Feature Request

### Describe the solution you'd like

I use the animation builder a lot and LOVE it.  I also like and use the loopchain nodes. It is evident from looking at fannovel's code that your work was an inspiration.  That suggests that hacking a loopchain input onto the animation builder wouldn't be a huge task. Having this would allow it to become a part of a larger animation scheme, facilitating a "one button" approach to a multi stage workflow.  

### Alternatives considered

I've considered hacking this myself but I hate working with javascript. 

### Additional context

I really feel like this would be a huge improvement, and since the input is optional, it wouldn't change the original nature of the node.  Thanks Mel!

**Comment by melMass** [comment]
I will catch up on loop chain I did not check it out yet!
