### ISSUE TITLE
Error occurred when executing Load Face Swap Model (mtb) [bug] 

### ISSUE THREAD

**Issue by conniecombs** [melMass/comfy_mtb#95]
### Describe the bug

I am getting an error when using Load Face Swap Model (mtb) using the inswapper_128.onnx model.

[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from G:\ComfyUI_windows_portable\ComfyUI\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.

File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\faceswap.py", line 98, in load_model
onnxruntime.InferenceSession(
File "G:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
self._create_inference_session(providers, provider_options, disabled_optimizers)
File "G:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)

Any assistance would be appreciated

### Reproduction

I have not been able to stop the behavior other than removing the node from the workflow

### Operating System

Windows (Default)

### Comfy Mode

Comfy Portable (embed) (Default)

### Console output

```sh
!!! Exception during processing !!!
Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\faceswap.py", line 98, in load_model
    onnxruntime.InferenceSession(
  File "G:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "G:\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from G:\ComfyUI_windows_portable\ComfyUI\models\insightface\inswapper_128.onnx failed:Protobuf parsing failed.
```

**Comment by melMass** [comment]
Hi please post logs in the section called Console output in the issue template.

The error is pretty clear: INVALID_PROTOBUF

There is a growing raise of issues here about onnx unfortunately none provide information useful to help sort it out. 

In your case I think it's just a protobuf compatibility issue.
If you know how to run pip you can just install protobuf==3.19.6 in your comfy env

**Comment by alenknight** [comment]
> custom_nodes\comfy_mtb\reqs_windows.txt

I'm having same issue.  how do you install dependencies from reqs_windows.txt?

**Comment by Famekrafts** [comment]
> I had the same issue, I was able to work around that on my own.
> 
> If you use Windows, first make sure you installed required dependencies from `custom_nodes\comfy_mtb\reqs_windows.txt`. If you use virtual environment, you can do it by typing.
> 
> ```powershell
> python -m venv venv
> .\venv\Scripts\pip.exe install -r .\custom_nodes\comfy_mtb\reqs_windows.txt
> ```
> 
> Be aware that [insightface removed their inswapper_128.onnx model from releases](https://github.com/deepinsight/insightface/issues/2294), and maintainer didn't update download URLs. File created is just a plain text file with "Not Found" or something like that. To get it fixed, you must find and download `inswapper_128.onnx` manually, then replace the corrupted model file in your `ComfyUI\models\insightface` directory. You can find the link to it in the issue comments in the URL above.
> 
> Same story with `buffalo_m` model. It can be found [here](https://github.com/deepinsight/insightface/tree/master/python-package#model-zoo).
> 
> Then I was successful with using both `inswapper_128.onnx` and `buffalo_m` with no issues.
> 
> As for `pth` models, they don't work with _Load Face Swap Model_. I think it's supposed to worth with `onnx` models anyway.
> 
> I also found [some additional PTH files to download](https://github.com/xinntao/facexlib/releases/tag/v0.1.0), but I'm not sure if they can be useful or not.

Where to install the buffalo file?

It is reading the inswapper_128.onx now but not reading the Buffalo file.

This is an error I get -
![face swap error](https://github.com/melMass/comfy_mtb/assets/146307016/696d875f-bcc5-456a-85a5-ed2fd2377961)

I am not a coder so no idea what error it is and cannot find anything on google about how to fix this.

**Comment by melMass** [comment]
@Famekrafts you probably did not run the install. There are issues with it that will get fixed this week so in the meantime:

Download anthelopev2 from here: https://drive.google.com/uc?id=18wEUfMNohBJ4K3Ly5wpTejPfDzp-8fI8

And extract it to "ComfyUI/models/insightface/models/antelopev2" like so:

![image](https://github.com/melMass/comfy_mtb/assets/7041726/e8feaf13-da50-456e-8cee-bd7637feb506)

**Comment by Famekrafts** [comment]
Ok Mel. I will wait for the issues to get fixed.

Till then I am using photoshop and image to image to swap faces.
